directive.o: directive.c ../util/util.h ../util/where.h \
 ../util/compiler.h ../util/dynarray.h ../util/dyn.h ../util/alloc.h \
 ../util/str.h directive.h tokenise.h main.h macro.h preproc.h include.h \
 str.h eval.h expr.h
eval.o: eval.c eval.h ../util/dynarray.h ../util/dyn.h ../util/util.h \
 ../util/where.h ../util/compiler.h ../util/alloc.h ../util/str.h \
 tokenise.h macro.h str.h main.h snapshot.h preproc.h
expr.o: expr.c ../util/alloc.h ../util/compiler.h ../util/util.h \
 ../util/where.h expr.h expr_tok.h main.h preproc.h
expr_tok.o: expr_tok.c expr.h expr_tok.h str.h preproc.h main.h \
 ../util/alloc.h ../util/compiler.h ../util/str.h ../util/util.h \
 ../util/where.h ../util/escape.h
include.o: include.c ../util/dynarray.h ../util/dyn.h ../util/alloc.h \
 ../util/compiler.h ../util/util.h ../util/where.h include.h main.h \
 preproc.h
macro.o: macro.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/alloc.h ../util/dynarray.h ../util/dyn.h macro.h main.h \
 preproc.h
main.o: main.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/dynarray.h ../util/dyn.h ../util/alloc.h ../util/platform.h \
 ../util/std.h ../util/limits.h main.h macro.h preproc.h include.h \
 directive.h
preproc.o: preproc.c ../util/util.h ../util/where.h ../util/compiler.h \
 ../util/alloc.h ../util/str.h main.h preproc.h directive.h eval.h str.h
snapshot.o: snapshot.c ../util/dynarray.h ../util/dyn.h ../util/alloc.h \
 ../util/compiler.h ../util/where.h snapshot.h macro.h
str.o: str.c str.h ../util/alloc.h ../util/compiler.h ../util/util.h \
 ../util/where.h ../util/str.h macro.h
tokenise.o: tokenise.c ../util/dynarray.h ../util/dyn.h ../util/alloc.h \
 ../util/compiler.h ../util/util.h ../util/where.h ../util/str.h \
 tokenise.h str.h
