str.o: str.c ../util/alloc.h ../util/compiler.h ../util/dynarray.h \
 ../util/dyn.h str.h
ucc.o: ucc.c ../config_driver.h ucc.h ucc_ext.h ucc_lib.h ../util/alloc.h \
 ../util/compiler.h ../util/dynarray.h ../util/dyn.h ../util/util.h \
 ../util/warn.h ../util/where.h ../util/platform.h ../util/tmpfile.h \
 str.h warning.h
ucc_ext.o: ucc_ext.c ../config_driver.h ucc_ext.h ucc.h ../util/alloc.h \
 ../util/compiler.h ../util/dynarray.h ../util/dyn.h str.h
ucc_lib.o: ucc_lib.c ucc.h ucc_ext.h ucc_lib.h str.h ../config_driver.h \
 ../util/alloc.h ../util/compiler.h ../util/dynarray.h ../util/dyn.h
warning.o: warning.c warning.h ../cpp2/warnings.def ../cc1/warnings.def
