pass: ./__asm__/decl.c
pass: ./__asm__/extern.c
fail: ./__asm__/inline.c
  ./__asm__/inline.c:6:5: ICW parse.c:232 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./__asm__/inline.c:6:7: warning: implicit declaration of function "__asm__"
    " asm("movl $3, %eax");"
          ^
  ./__asm__/inline.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "__asm__", referenced from:
        main in tmp.2.fGX5hE
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./__asm__/inline.c -o ./inline.out' failed
fail: ./__asm__/multiple.c
  ./__asm__/multiple.c:8:5: ICW parse.c:232 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./__asm__/multiple.c:10:5: warning: implicit declaration of function "__asm__"
    "   "ret\n");"
        ^
  ./__asm__/multiple.c:11:8: warning: implicit declaration of function "abort"
    " abort();"
           ^
  ./__asm__/multiple.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "__asm__", referenced from:
        main in tmp.2.HWQTkp
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc -o ./multiple.out ./__asm__/multiple.c' failed
pass: ./__attribute__/_Noreturn.c
pass: ./__attribute__/attr_simple.c
fail: ./__attribute__/awkward.c
  ./__attribute__/awkward.c:7:22: error: expecting token open_block, got int (parse.c:779)
    " __attribute__(()) int i;"
                         ^
  ./__attribute__/awkward.c:13:1: error: expecting token semicolon, got open_block (parse.c:921)
    "{"
    ^
  ./__attribute__/awkward.c:15:1: error: expression expected, got eof (parse.c:239)
    "}"
    ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc ./__attribute__/awkward.c -o ./awkward.out' failed
fail: ./__attribute__/nonnull.c
  check /warning nonnull attribute on parameterless function/ not found in warnings on line 8
  check /nonnull attribute applied to non-pointer argument 'int'/ not found in warnings on line 12
  check /null passed where non-null required (arg 1)/ not found in warnings on line 16
  ./test.pl: command './check.sh ./__attribute__/nonnull.c' failed
pass: ./__attribute__/nonnull_simple.c
fail: ./__attribute__/prototypes.c
  ./__attribute__/prototypes.c:8:10: warning: function "_exit" marked no-return implicitly returns
    "void _exit(int x) __attribute__((__noreturn__)) "
             ^
  ./__attribute__/prototypes.c:8:16: warning: "x" never read
    "void _exit(int x) __attribute__((__noreturn__)) "
                   ^
  check !/warn/ not found in warnings on line 8
  ./test.pl: command './check.sh ./__attribute__/prototypes.c' failed
pass: ./__attribute__/reachability.c
fail: ./__attribute__/sentinel.c
  ./__attribute__/sentinel.c:14:10: warning: sentinel argument expected (got int)
    " f(1, 2, 3); "
             ^
  ./__attribute__/sentinel.c:17:25: warning: sentinel argument expected (got int)
    " f(1, 2, 3, (void *)0, 2); "
                            ^
  ./__attribute__/sentinel.c:18:8: warning: sentinel argument expected (got int)
    " f(1, 0); "
           ^
  ./__attribute__/sentinel.c:22:46: warning: sentinel argument expected (got int)
    " f(1, 2, 3, (void *)0, 5, 6, 7, (void *)0, 2);  "
                                                 ^
  ./__attribute__/sentinel.c:24:8: warning: sentinel argument expected (got int)
    " g(1, 0); "
           ^
  ./__attribute__/sentinel.c:25:5: warning: not enough variadic arguments for a sentinel
    " g(0);    "
        ^
  ./__attribute__/sentinel.c:27:4: warning: not enough variadic arguments for a sentinel
    " h(5);            "
       ^
  ./__attribute__/sentinel.c:28:4: warning: sentinel index is not a variadic argument
    " h(5, (void *)0); "
       ^
  ./__attribute__/sentinel.c:29:19: warning: sentinel argument expected (got int)
    " h(5, (void *)0, 2, 3); "
                      ^
  ./__attribute__/sentinel.c:32:4: warning: not enough variadic arguments for a sentinel
    " k(1); "
       ^
  ./__attribute__/sentinel.c:34:22: warning: sentinel argument expected (got int)
    " k(1, 2, (void *)0, 3, 3, 3, 4); "
                         ^
  ./__attribute__/sentinel.c:37:4: warning: variadic function required for sentinel check
    " r(5);"
       ^
  ./__attribute__/sentinel.c:12:4: warning: control reaches end of non-void function main
    "main()"
       ^
  check /warning: sentinel on non-variadic function/ not found in warnings on line 10
  check /warning: missing sentinel/ not found in warnings on line 14
  check /warning: missing sentinel/ not found in warnings on line 17
  check /warning: missing sentinel/ not found in warnings on line 18
  ./check.pl: invalid CHECK: '/warning: missing sentinel'
  ./test.pl: command './check.sh ./__attribute__/sentinel.c' failed
pass: ./__attribute__/underscore.c
pass: ./__builtin/bfa.c
pass: ./__builtin/is_signed.c
fail: ./__builtin/strlen_k.c
  ./__builtin/strlen_k.c:6:1: warning: control reaches end of non-void function q
    "q(){}"
    ^
  ./__builtin/strlen_k.c:7:6: warning: initialisation type mismatch: char * <-- const char *
    "char *s = "";"
         ^
  ./__builtin/strlen_k.c:11:9: warning: implicit declaration of function "strlen"
    " strlen(s);"
            ^
  ./__builtin/strlen_k.c:17:9: warning: implicit declaration of function "abort"
    "  abort();"
            ^
  sh: line 1:  7668 Segmentation fault: 11  ./strlen_k.out
  ./test.pl: command './strlen_k.out; [ $? -eq 8 ]' failed
pass: ./anywhere_decl/decl.c
fail: ./anywhere_decl/loop.c
  ./anywhere_decl/loop.c:12:7: warning: mixed code and declarations
    "  int j = 3;"
          ^
  ./anywhere_decl/loop.c:5:1: warning: control reaches end of non-void function x
    "x(){}"
    ^
  ./anywhere_decl/loop.c:14:11: warning: implicit declaration of function "printf"
    "  printf("%d, %d\n", i, j);"
              ^
  ./anywhere_decl/loop.c:15:3: warning: unused expression (identifier)
    "  j;"
      ^
  ./anywhere_decl/loop.c:7:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./test.pl: command './loop.out | grep '0, 3'' failed
pass: ./anywhere_decl/parse.c
pass: ./anywhere_decl/shadow.c
fail: ./arrays/bounds.c
  check /index 3 out of bounds.*3/ not found in warnings on line 13
  check /index 2 out of bounds.*2/ not found in warnings on line 27
  check /index -5 out of bounds.*2/ not found in warnings on line 32
  ./test.pl: command './check.sh ./arrays/bounds.c' failed
fail: ./arrays/bounds_add.c
  check /index 2 out of bounds/ not found in warnings on line 7
  ./test.pl: command './check.sh ./arrays/bounds_add.c' failed
pass: ./arrays/bounds_one_after.c
fail: ./arrays/bounds_parse.c
  ./arrays/bounds_parse.c:8:14: warning: index -2 out of bounds of array, size 4
    " return (-2)[x] "
                 ^
  check !/index.*out of bounds.*2/ not found in warnings on line 9
  ./test.pl: command './check.sh ./arrays/bounds_parse.c' failed
fail: ./arrays/invalid_inc.c
  check /error: dereference of pointer to incom/ not found in warnings on line 5
  ./test.pl: command './check.sh -e ./arrays/invalid_inc.c' failed
pass: ./arrays/op_order.c
pass: ./arrays/opt_load.c
fail: ./arrays/ptr.c
  ./arrays/ptr.c:3:14: error: dereference of pointer to incomplete type int []
    "f(int (*pa)[])"
                 ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./arrays/ptr.c' failed
fail: ./arrays/stride_nx2x4.c
  ./arrays/stride_nx2x4.c:8:11: warning: index 1 out of bounds of array, size 0
    " return x[1][2][3]; "
              ^
  ./arrays/stride_nx2x4.c:4:15: error: dereference of pointer to incomplete type int ([])[2][4]
    "extern int x[][2][4];"
                  ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./arrays/stride_nx2x4.c' failed
fail: ./arrays/stride_nx3.c
  ./arrays/stride_nx3.c:12:4: warning: index 1 out of bounds of array, size 0
    "  [1]  "
       ^
  ./arrays/stride_nx3.c:21:4: warning: index 2 out of bounds of array, size 0
    "  [2]  "
       ^
  ./arrays/stride_nx3.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./arrays/stride_nx3.c:8:16: error: dereference of pointer to incomplete type int ([])[3]
    " extern int a[][3];"
                   ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./arrays/stride_nx3.c' failed
fail: ./arrays/strlen_2.c
  ./arrays/strlen_2.c:2:16: warning: implicit declaration of function "strlen"
    "char x[strlen("yo") - 1];"
                   ^
  ./arrays/strlen_2.c:2:22: error: not a numeric constant for array size
    "char x[strlen("yo") - 1];"
                         ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./arrays/strlen_2.c' failed
fail: ./asm/abi-test.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
pass: ./asm/abi_vararg_nulfptr.c
pass: ./asm/asm_bend.c
pass: ./asm/assigns.c
fail: ./asm/call.c
  todo
  ./test.pl: command 'echo todo; false' failed
pass: ./asm/call_or.c
pass: ./asm/call_ptr.c
pass: ./asm/cast.c
pass: ./asm/cmp.c
pass: ./asm/complex_math.c
pass: ./asm/compound_assign.c
pass: ./asm/compound_increment.c
fail: ./asm/computed_goto.c
  ../ucc: cc1/cc1 caught signal 9
  ./test.pl: command '../ucc -o ./computed_goto.out ./asm/computed_goto.c' failed
pass: ./asm/different_sizes.c
pass: ./asm/div.c
pass: ./asm/expr-if.c
pass: ./asm/goto.c
pass: ./asm/inc.c
pass: ./asm/jmp.c
pass: ./asm/kjmp.c
pass: ./asm/lea.c
fail: ./asm/load-time-constant.c
  ./asm/load-time-constant.c:6:1: warning: initialisation type mismatch: int <-- int *
    "i = &j;"
    ^
  (null):6:7: ICE gen_asm.c:62 (static_addr): non-constant expr-cast const=0
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -c ./asm/load-time-constant.c' failed
pass: ./asm/memory.c
pass: ./asm/mismatch_compound.c
fail: ./asm/offsetof.c
  ./asm/offsetof.c:10:23: error: global scalar initialiser not constant
    "const int static i =  ((int)&((struct A *)0)->x);"
                          ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./asm/offsetof.c' failed
pass: ./asm/pointers.c
pass: ./asm/shft.c
pass: ./asm/store.c
pass: ./asm/x86_shift.c
pass: ./assignment/assign_check.c
pass: ./assignment/valid1.c
fail: ./bitfields/bitfield_warns.c
  ./bitfields/bitfield_warns.c:8:19: ICE parse_type.c:937 (parse_decls_multi_type): TODO: field width
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc ./bitfields/bitfield_warns.c' failed
pass: ./blocks/basic.c
pass: ./blocks/block_const.c
fail: ./blocks/block_decl.c
  ./blocks/block_decl.c:6:12: warning: control reaches end of non-void function dispatch
    "int dispatch(int x(char))"
               ^
  ./blocks/block_decl.c:13:10: warning: implicit declaration of function "printf"
    " printf("%c\n", c);"
             ^
  ./blocks/block_decl.c:11:2: warning: control reaches end of non-void function pc
    "pc(char c)"
     ^
  ./blocks/block_decl.c:18:42: warning: implicit declaration of function "printf"
    " int (^x)(char) = ^int(char tim){printf("%c\n", tim);};"
                                             ^
  ./blocks/block_decl.c:20:7: warning: initialisation type mismatch: void (^)(void) <-- int
    " void (^z)(void) = 0;"
          ^
  ./blocks/block_decl.c:16:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./blocks/block_decl.c:20:7: warning: "z" never read
    " void (^z)(void) = 0;"
          ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './block_decl.out | ./ocheck.pl '^a$' '^a$' '^a$' '^B$'' failed
fail: ./blocks/block_ret.c
  ./blocks/block_ret.c:8:40: warning: implicit declaration of function "printf"
    " int (^f)(int) = ^int (int i) {printf("hi %d\n", i); return 0;};"
                                           ^
  ./blocks/block_ret.c:10:10: warning: implicit declaration of function "printf"
    " printf("%c\n", ^char {"
             ^
  sh: line 1:  8221 Segmentation fault: 11  ./block_ret.out
  ./test.pl: command './block_ret.out; [ $? -eq 0 ]' failed
pass: ./blocks/blocks_args.c
fail: ./blocks/blocks_simple.c
  ./blocks/blocks_simple.c:8:44: warning: mismatching return type for main (int <-- int *)
    " int *(^q)() = ^{ static int i = 2; return &i; };"
                                               ^
  ./blocks/blocks_simple.c:8:6: warning: initialisation type mismatch: int *((^)()) <-- int (^)(void)
    " int *(^q)() = ^{ static int i = 2; return &i; };"
         ^
  ./blocks/blocks_simple.c:10:10: warning: implicit declaration of function "printf"
    " printf("%d\n", *q());"
             ^
  ./blocks/blocks_simple.c:13:11: warning: implicit declaration of function "printf"
    "  printf("hi\n");"
              ^
  ./blocks/blocks_simple.c:17:12: warning: implicit declaration of function "printf"
    " ^{printf("inline call\n");}();"
               ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './blocks_simple.out | ./ocheck.pl '^2$' '^inline call$' '^hi$'' failed
fail: ./blocks/blocks_state.c
  ./blocks/blocks_state.c:8:25: warning: mismatching return type for makeadder (int (^)(int) <-- int)
    " return ^(int a){return a + the_i;};"
                            ^
  ./blocks/blocks_state.c:8:9: warning: mismatching return type for makeadder (int (^)(int) <-- int (^((^)(int a)))(int))
    " return ^(int a){return a + the_i;};"
            ^
  ./blocks/blocks_state.c:17:10: warning: implicit declaration of function "printf"
    " printf("%d\n", (*i)());"
             ^
  ./blocks/blocks_state.c:24:27: warning: implicit declaration of function "printf"
    " ^(const char *s){printf("%s\n", s);}("hi");"
                              ^
  ./blocks/blocks_state.c:11:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './blocks_state.out | ./ocheck.pl '^2$' '^7$' '^5$' '^hi$'' failed
pass: ./blocks/deep.c
pass: ./blocks/equal.c
pass: ./blocks/folding.c
pass: ./blocks/full_decl.c
pass: ./blocks/nest.c
fail: ./builtin/all.c
  ./builtin/all.c:6:11: warning: control reaches end of non-void function not_builtin
    "not_builtin()"
              ^
  ./builtin/all.c:15:18: warning: dead code after goto (expr)
    " __builtin_trap();"
                     ^
  Can't exec "./all.out": No such file or directory at ./timeout line 13.
  ./timeout: exec './all.out'...: No such file or directory
  ./test.pl: command './all.out' failed
pass: ./builtin/expect.c
fail: ./builtin/frame_address.c
  ./builtin/frame_address.c:8:10: warning: implicit declaration of function "printf"
    " printf("%d\n", i);"
             ^
  ./builtin/frame_address.c:8:12: warning: "i" uninitialised on read
    " printf("%d\n", i);"
               ^
  ./builtin/frame_address.c:3:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './frame_address.out | ./ocheck.pl '^3$'' failed
fail: ./builtin/propagation.c
  sh: ./propagation.out: No such file or directory
  ./test.pl: command './propagation.out; [ $? -eq 1 ]' failed
pass: ./builtin/sizeof.c
fail: ./builtin/unused.c
  ../ucc: cc1/cc1 caught signal 9
  ./test.pl: command '../ucc ./builtin/unused.c' failed
fail: ./C99/C99_for.c
  (null):14:1: ICE out/out.c:69 (vpop): NULL vtop for vpop
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -o ./C99_for.out ./C99/C99_for.c' failed
fail: ./C99/enum_scope.c
  error expected
  ./C99/enum_scope.c:5:10: warning: mismatching return type for main (int <-- enum <anon enum 0x10cb00f48>)
    "  return a;"
             ^
  ./C99/enum_scope.c:6:9: warning: mismatching return type for main (int <-- enum <anon enum 0x10cb00f48>)
    " return b; "
            ^
  ./test.pl: command './check.sh -e ./C99/enum_scope.c' failed
fail: ./C99/generic_complex.c
  ./C99/generic_complex.c:9:29: error: trying to redefine union as struct (from ./C99/generic_complex.c:8:44)
    "    , char: 5, int(struct f): 1);"
                                ^
  ../ucc: cc1/cc1 returned 1
  sh: ./generic_complex.out: No such file or directory
  ./test.pl: command './generic_complex.out; [ $? -eq 1 ]' failed
fail: ./C99/generic_default.c
  (null):7:1: ICE fold.c:112 (FOLD_EXPR_NO_DECAY): no tree_type after fold (_Generic)
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -o ./generic_default.out ./C99/generic_default.c' failed
pass: ./C99/generic_dup.c
pass: ./C99/generic_nomatch.c
fail: ./C99/generic_simple.c
  (null):7:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -o ./generic_simple.out ./C99/generic_simple.c' failed
pass: ./casts/bool.c
pass: ./casts/const_cast.c
fail: ./casts/ineq_ptr.c
  ./casts/ineq_ptr.c:10:4: warning: implicit declaration of function "q"
    " q(a == (char *)0); "
       ^
  ./casts/ineq_ptr.c:10:4: warning: "a" uninitialised on read
    " q(a == (char *)0); "
       ^
  ./casts/ineq_ptr.c:10:7: warning: comparison of distinct pointer types lacks a cast (i_td (aka 'int') * vs char *)
    " q(a == (char *)0); "
          ^
  ./casts/ineq_ptr.c:12:16: warning: assignment type mismatch: i_td (aka 'int') * <-- short *
    " a = (short *)5; "
                   ^
  ./casts/ineq_ptr.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "q", referenced from:
        main in tmp.2.H7W8a3
       (maybe you meant: quick_exit, at_quick_exit )
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./casts/ineq_ptr.c' failed
fail: ./casts/invalid.c
  assuming "etc" is object-file
  assuming "etc..." is object-file
  ld: file not found: etc
  ../ucc: ld returned 1
  ./test.pl: command '../ucc -DTYPE='int[]' etc etc...' failed
pass: ./casts/invalid_bool.c
pass: ./cil/1.c
pass: ./cil/2.c
pass: ./cil/3.c
pass: ./cil/4.c
pass: ./cil/5.c
pass: ./cil/6.c
pass: ./cil/7.c
pass: ./cil/8.c
fail: ./cil/9.c
  ./test.pl: command '../ucc -o ./9.out ./cil/9.c && ./9.out' failed
pass: ./cil/cil_1.c
fail: ./cil/gcc_1.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
pass: ./cil/gcc_2.c
pass: ./cil/gcc_3.c
fail: ./cil/gcc_4.c
  ./cil/gcc_4.c:4:21: warning: dead code after goto (expr)
    " return ({goto L; 0;}) && ({L: 5;});"
                        ^
  ./cil/gcc_4.c:4:33: warning: unused expression (val)
    " return ({goto L; 0;}) && ({L: 5;});"
                                    ^
  ./cil/gcc_4.c:4:26: error: use of void expression
    " return ({goto L; 0;}) && ({L: 5;});"
                             ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -o ./gcc_4.out ./cil/gcc_4.c && (./gcc_4.out; [ $? -eq 5 ])' failed
pass: ./cil/gcc_5.c
fail: ./cil/gcc_6.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
fail: ./cil/gcc_7.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
fail: ./cil/gcc_8.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
fail: ./clang/declarators.c
  ./test.pl: undefined variable %clang_cc in ./clang/declarators.c
fail: ./clang/expressions.c
  ./test.pl: undefined variable %clang_cc in ./clang/expressions.c
fail: ./clang/if-scope.c
  ./test.pl: undefined variable %clang_cc in ./clang/if-scope.c
fail: ./clang/proto-promote.c
  ./test.pl: undefined variable %clang_cc in ./clang/proto-promote.c
fail: ./clang/ptr-arith.c
  ./test.pl: undefined variable %clang_cc in ./clang/ptr-arith.c
fail: ./clang/ptr-promote.c
  ./test.pl: undefined variable %clang_cc in ./clang/ptr-promote.c
fail: ./clang/stmts.c
  ./test.pl: undefined variable %clang_cc in ./clang/stmts.c
fail: ./clang/switch.c
  ./test.pl: undefined variable %clang_cc in ./clang/switch.c
fail: ./clang/typeof.c
  ./test.pl: undefined variable %clang_cc in ./clang/typeof.c
fail: ./clang/types.c
  ./test.pl: undefined variable %clang_cc in ./clang/types.c
pass: ./code_gen/vtop_check.c
pass: ./compound_literal/add.c
pass: ./compound_literal/addr.c
fail: ./compound_literal/adv_addr.c
  ./compound_literal/adv_addr.c:8:20: warning: assignment type mismatch: int (*)[] <-- int (*)[2]
    " p = &(int[]){1, 2};"
                       ^
  ./compound_literal/adv_addr.c:6:12: error: dereference of pointer to incomplete type int []
    " int (*p)[];"
               ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -o ./adv_addr.out ./compound_literal/adv_addr.c' failed
pass: ./compound_literal/c-lit.c
fail: ./compound_literal/global.c
  ./compound_literal/global.c:4:9: error: global scalar initialiser not constant
    "int i = (int){1};"
            ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -o ./global.out ./compound_literal/global.c' failed
pass: ./compound_literal/nested_several.c
pass: ./compound_literal/ptr.c
pass: ./compound_literal/sizeof.c
fail: ./const/const_int.c
  ./const/const_int.c:9:7: error: can't modify const expression identifier
    " x = 2; "
          ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./const/const_int.c:9:7: error: can't modify const expression identifier
    " x = 2; "
          ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./const/const_int.c' failed
pass: ./cpp/count_params.c
pass: ./cpp/cpp.c
fail: ./cpp/overload.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
pass: ./decay/array.c
fail: ./decay/assign.c
  no error expected
  ./decay/assign.c:6:2: error: not an lvalue (identifier)
    " a = 3; "
     ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./decay/assign.c' failed
fail: ./decay/typeof.c
  ./decay/typeof.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  sh: -c: line 0: unexpected EOF while looking for matching ``'
  sh: -c: line 1: syntax error: unexpected end of file
  ./test.pl: command '[ `../ucc -S -o- ./decay/typeof.c | grep 'subq'` | awk '{print $2}' | sed 's#.0x##'` -ge 48 ]' failed
pass: ./decay/unary_addr_and_sizeof.c
pass: ./decl_parsing/add_or_sub.c
pass: ./decl_parsing/ar.c
pass: ./decl_parsing/arg.c
fail: ./decl_parsing/atexit/atexit.c
  ./decl_parsing/atexit/atexit.c:5:10: warning: implicit declaration of function "printf"
    " printf("beet\n");"
             ^
  ./decl_parsing/atexit/atexit.c:3:4: warning: control reaches end of non-void function p_hi
    "p_hi()"
       ^
  ./decl_parsing/atexit/atexit.c:10:10: warning: implicit declaration of function "printf"
    " printf("bye\n");"
             ^
  ./decl_parsing/atexit/atexit.c:8:5: warning: control reaches end of non-void function p_bye
    "p_bye()"
        ^
  ./decl_parsing/atexit/atexit.c:15:12: warning: implicit declaration of function "atexit"
    " atexit(p_hi);"
               ^
  ./decl_parsing/atexit/atexit.c:13:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './atexit.out | ./ocheck.pl '^bye$' '^beet$'' failed
fail: ./decl_parsing/atexit/atexit2.c
  ./decl_parsing/atexit/atexit2.c:6:3: warning: control reaches end of non-void function add
    "add(int (*f)())"
      ^
  ./decl_parsing/atexit/atexit2.c:11:3: warning: control reaches end of non-void function run
    "run()"
      ^
  ./decl_parsing/atexit/atexit2.c:17:13: warning: implicit declaration of function "printf"
    "a(){printf("a\n");}"
                ^
  ./decl_parsing/atexit/atexit2.c:17:1: warning: control reaches end of non-void function a
    "a(){printf("a\n");}"
    ^
  ./decl_parsing/atexit/atexit2.c:18:13: warning: implicit declaration of function "printf"
    "b(){printf("b\n");}"
                ^
  ./decl_parsing/atexit/atexit2.c:18:1: warning: control reaches end of non-void function b
    "b(){printf("b\n");}"
    ^
  ./decl_parsing/atexit/atexit2.c:20:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './atexit2.out | ./ocheck.pl a b' failed
fail: ./decl_parsing/atexit/atexit_simplified.c
  ./decl_parsing/atexit/atexit_simplified.c:7:3: warning: control reaches end of non-void function add
    "add(void (*f)())"
      ^
  ./decl_parsing/atexit/atexit_simplified.c:15:10: warning: implicit declaration of function "printf"
    " printf("fs = %p\n", fs);"
             ^
  ./decl_parsing/atexit/atexit_simplified.c:12:3: warning: control reaches end of non-void function run
    "run()"
      ^
  ./decl_parsing/atexit/atexit_simplified.c:22:21: warning: implicit declaration of function "printf"
    " void a(){printf("a" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:23:21: warning: implicit declaration of function "printf"
    " void b(){printf("b" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:24:21: warning: implicit declaration of function "printf"
    " void c(){printf("c" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:26:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './atexit_simplified.out | ./ocheck.pl a b c' failed
fail: ./decl_parsing/fptr.c
  ./decl_parsing/fptr.c:6:10: warning: implicit declaration of function "printf"
    " printf("inst(%d)\n", i);"
             ^
  ./decl_parsing/fptr.c:20:4: warning: unused expression (deref)
    " *f;"
       ^
  ./decl_parsing/fptr.c:9:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './fptr.out | ./ocheck.pl 1 2 3 4 5 7 3 3' failed
fail: ./decl_parsing/fptr_arg.c
  ./test.pl: undefined variable %ocheck in ./decl_parsing/fptr_arg.c
fail: ./decl_parsing/fptr_get.c
  ./decl_parsing/fptr_get.c:5:10: warning: implicit declaration of function "printf"
    " printf("yo\n");"
             ^
  ./decl_parsing/fptr_get.c:3:5: warning: control reaches end of non-void function x
    "int x()"
        ^
  mismatching output counts at ./ocheck.pl line 15.
  ./test.pl: command './fptr_get.out | ./ocheck.pl yo' failed
fail: ./decl_parsing/func_array.c
  ./decl_parsing/func_array.c:11:25: warning: implicit declaration of function "printf"
    " void p1(int i){printf("%s %d\n", __func__, i);}"
                            ^
  ../ucc: cc1/cc1 caught signal 11
  ./test.pl: command '../ucc ./decl_parsing/func_array.c -o ./func_array.out' failed
pass: ./decl_parsing/parse_test.c
fail: ./decl_parsing/ptr.c
  ./test.pl: undefined variable %ocheck in ./decl_parsing/ptr.c
fail: ./decl_parsing/simple.c
  ./test.pl: undefined variable %ocheck in ./decl_parsing/simple.c
fail: ./decl_parsing/st_fn.c
  ./decl_parsing/st_fn.c:5:14: warning: implicit declaration of function "printf"
    "p1(){printf("yo\n");}"
                 ^
  ./decl_parsing/st_fn.c:5:2: warning: control reaches end of non-void function p1
    "p1(){printf("yo\n");}"
     ^
  ./decl_parsing/st_fn.c:15:10: warning: assignment type mismatch: void (*)(void) <-- int (*)()
    " f.f = p1;"
             ^
  ./test.pl: undefined variable %ocheck in ./decl_parsing/st_fn.c
pass: ./driver/output-fail.c
pass: ./enum/enum.c
fail: ./format/fmt.c
  ./format/fmt.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  check !/warn/ not found in warnings on line 7
  ./test.pl: command './check.sh ./format/fmt.c' failed
fail: ./format/fmt_invalid.c
  ./format/fmt_invalid.c:9:5: warning: mismatching argument 2 to f (char * <-- const char *)
    " f(0, 0, "hi", 2);"
        ^
  ./format/fmt_invalid.c:9:5: error: variadic argument at format argument
    " f(0, 0, "hi", 2);"
        ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc ./format/fmt_invalid.c' failed
fail: ./format/mismatch.c
  ./format/mismatch.c:7:13: warning: format %d expects integral argument
    " printf("hello %d\n", "yo"); "
                ^
  ./format/mismatch.c:8:12: warning: format %s expects 'char *' argument
    " printf("hello %s\n", 2); "
               ^
  ./format/mismatch.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./test.pl: undefined variable %d in ./format/mismatch.c
fail: ./format/non_trivial_fmt.c
  ./format/non_trivial_fmt.c:7:9: warning: mismatching argument 0 to printf (char * <-- const char *)
    " printf(a ? "b=%d (a=%s)\n" : "b=%d\n", b, a); "
            ^
  ./format/non_trivial_fmt.c:7:23: warning: format %s expects 'char *' argument
    " printf(a ? "b=%d (a=%s)\n" : "b=%d\n", b, a); "
                          ^
  ./format/non_trivial_fmt.c:7:9: warning: too many arguments for format
    " printf(a ? "b=%d (a=%s)\n" : "b=%d\n", b, a); "
            ^
  ./format/non_trivial_fmt.c:4:1: warning: control reaches end of non-void function f
    "f(int a, int b)"
    ^
  Undefined symbols for architecture x86_64:
    "main", referenced from:
        _start in crt.o
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./format/non_trivial_fmt.c' failed
fail: ./format/non_variadic.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./format/non_variadic.c'...: No such file or directory
  ./test.pl: command '! ../ucc ./format/non_variadic.c' failed
pass: ./format/null.c
fail: ./format/str.c
  ./format/str.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  check !/warn/ not found in warnings on line 8
  ./test.pl: command './check.sh ./format/str.c' failed
fail: ./format/too_few.c
  ./format/too_few.c:7:10: warning: too few arguments for format (%d)
    " printf("hi %d\n"); "
             ^
  ./format/too_few.c:8:10: warning: too few arguments for format (%s)
    " printf("hi %d %s\n", 2); "
             ^
  ./format/too_few.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  check /warning: too few arguments for format (%d)/ not found in warnings on line 7
  check /warning: too few arguments for format (%s)/ not found in warnings on line 8
  ./test.pl: command './check.sh ./format/too_few.c' failed
pass: ./format/too_many.c
fail: ./functions/stret.c
  ./functions/stret.c:3:20: warning: function "p" marked no-return has a non-void return value
    "_Noreturn struct A *p()"
                       ^
  Undefined symbols for architecture x86_64:
    "main", referenced from:
        _start in crt.o
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./functions/stret.c' failed
fail: ./gasm/gasm.c
  ./test.pl: undefined variable %ocheck in ./gasm/gasm.c
pass: ./gasm/gasm_order.c
fail: ./gen/flag_argument.c
  ./gen/flag_argument.c:7:4: warning: implicit declaration of function "f"
    " f((char *)0 == i);"
       ^
  ./gen/flag_argument.c:7:18: warning: "i" uninitialised on read
    " f((char *)0 == i);"
                     ^
  ./gen/flag_argument.c:7:16: warning: comparison of distinct pointer types lacks a cast (char * vs int *)
    " f((char *)0 == i);"
                   ^
  ./gen/flag_argument.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "f", referenced from:
        main in tmp.2.oDzire
       (maybe you meant: fork, fdopendir , fflush , dirfd , printf , fopen , dprintf , fileno , fwrite , freopen , fputc , vprintf , fgetc , fprintf , fclose , fsetpos , ferror , fgets , fropen , fdopen , fputs , ftell , fgetpos , free , feof , funopen , fseek , fwopen , vfprintf , __assert_fail , fread )
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./gen/flag_argument.c' failed
fail: ./gen/for_C99.c
  ./gen/for_C99.c:5:10: warning: "i" never read
    " for(int i =0;;);"
             ^
  (null):7:1: ICE out/out.c:69 (vpop): NULL vtop for vpop
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc ./gen/for_C99.c' failed
pass: ./initialisation/array/brace.c
pass: ./initialisation/array/nobrace.c
pass: ./initialisation/array/normal.c
fail: ./initialisation/array/variations.c
  ./initialisation/array/variations.c:9:12: warning: implicit declaration of function "printf"
    "   printf("[%d][%d] = %d\n", i, j, a[i][j]);"
               ^
  ./initialisation/array/variations.c:4:1: warning: control reaches end of non-void function p
    "p(int (*a)[2])"
    ^
  ./initialisation/array/variations.c:12:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/array/variations.c:9:12: warning: implicit declaration of function "printf"
    "   printf("[%d][%d] = %d\n", i, j, a[i][j]);"
               ^
  ./initialisation/array/variations.c:4:1: warning: control reaches end of non-void function p
    "p(int (*a)[2])"
    ^
  ./initialisation/array/variations.c:12:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./test.pl: command '[ `../ucc ./initialisation/array/variations.c -S -o- | grep 'mov.*[0123]' | wc -l` -eq 12 ]' failed
pass: ./initialisation/compound/funcall.c
pass: ./initialisation/compound/ptr.c
pass: ./initialisation/compound/sizeof_parsing.c
fail: ./initialisation/compound/undefined.c
  TODO ./initialisation/compound/undefined.c
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_global/addr_global.c
  TODO ./initialisation/compound_global/addr_global.c
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_global/and_static.c
  TODO ./initialisation/compound_global/and_static.c
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_global/cast_lit.c
  ./initialisation/compound_global/cast_lit.c:3:9: error: global scalar initialiser not constant
    "int i = (int)(int){5};"
            ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -S -o- ./initialisation/compound_global/cast_lit.c | grep -E '\.long +5'' failed
fail: ./initialisation/compound_global/yes_no_cases.c
  TODO ./initialisation/compound_global/yes_no_cases.c
  ./test.pl: command 'false' failed
pass: ./initialisation/compound_lit/basic.c
fail: ./initialisation/compound_lit/nested.c
  ./initialisation/compound_lit/nested.c:6:6: warning: initialisation type mismatch: int * <-- int (*)[2]
    " int *p = (int[][2]){"
         ^
  ./initialisation/compound_lit/nested.c:6:6: error: invalid indirection applied to int
    " int *p = (int[][2]){"
         ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -o ./nested.out ./initialisation/compound_lit/nested.c' failed
pass: ./initialisation/compound_lit/sizeof.c
fail: ./initialisation/designated/all_3.c
  ./test.pl: undefined variable %layoutcheck in ./initialisation/designated/all_3.c
fail: ./initialisation/designated/array/basic.c
  ./test.pl: undefined variable %ocheck in ./initialisation/designated/array/basic.c
fail: ./initialisation/designated/array/bounds.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./initialisation/designated/array/bounds.c'...: No such file or directory
  ./test.pl: command '! ../ucc ./initialisation/designated/array/bounds.c' failed
fail: ./initialisation/designated/array/of_structs.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/designated/array/of_structs.c' failed
fail: ./initialisation/designated/array_nested_struct.c
  TODO ./initialisation/designated/array_nested_struct.c
  ./test.pl: command 'false' failed
fail: ./initialisation/designated/arrays.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/designated/arrays.c' failed
fail: ./initialisation/designated/backwards_struct.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/designated/backwards_struct.c' failed
fail: ./initialisation/designated/desig_array_st.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/designated/desig_array_st.c' failed
fail: ./initialisation/designated/struct/sub_desig.c
  ./test.pl: undefined variable %ocheck in ./initialisation/designated/struct/sub_desig.c
fail: ./initialisation/designated/struct/various_desig.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/designated/struct/various_desig.c' failed
fail: ./initialisation/designated/unordered_struct.c
  ./initialisation/designated/unordered_struct.c:13:2: warning: excess initialiser for struct
    " 3, "
     ^
  check /warning: excess struct initialiser/ not found in warnings on line 13
  ./test.pl: command './check.sh ./initialisation/designated/unordered_struct.c' failed
fail: ./initialisation/global/address_cast.c
  ./initialisation/global/address_cast.c:6:10: error: global scalar initialiser not constant
    "int *p = (int)&x; "
             ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./initialisation/global/address_cast.c:6:10: error: global scalar initialiser not constant
    "int *p = (int)&x; "
             ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./initialisation/global/address_cast.c' failed
fail: ./initialisation/global/array.c
  ./test.pl: command '[ `../ucc ./initialisation/global/array.c -S -o- | grep '[1234]' | wc -l` -eq 16 ]' failed
fail: ./initialisation/global/array_init.c
  ./test.pl: undefined variable %ocheck in ./initialisation/global/array_init.c
fail: ./initialisation/global/compound_lit_and_str.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/compound_lit_and_str.c' failed
fail: ./initialisation/global/compound_literal.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/compound_literal.c' failed
fail: ./initialisation/global/compound_literal_addr_off.c
  ./test.pl: undefined variable %ocheck in ./initialisation/global/compound_literal_addr_off.c
pass: ./initialisation/global/const_shortcircuit.c
fail: ./initialisation/global/empty.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/empty.c' failed
pass: ./initialisation/global/global_negative.c
fail: ./initialisation/global/globals.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/globals.c' failed
fail: ./initialisation/global/offsetof.c
  ./test.pl: undefined variable %ocheck in ./initialisation/global/offsetof.c
fail: ./initialisation/global/static_addr.c
  ./initialisation/global/static_addr.c:8:18: error: static scalar initialiser not constant
    " static int *p = &a;"
                     ^
  ../ucc: cc1/cc1 returned 1
  ./initialisation/global/static_addr.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/global/static_addr.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "a", referenced from:
        main.static1_p in tmp.2.dK53i0
       (maybe you meant: main, mmap , scandir , readdir , isalpha , isalnum , isblank , __progname , isspace , realloc , readlink , nanosleep , isascii , abort , at_quick_exit , alloca , munmap , _start , putchar , malloc , getchar , isgraph , __syscall , read , atoi , waitpid , atexit_b , atexit , __assert_fail , raise , calloc , fread )
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc -DSTORE=extern ./initialisation/global/static_addr.c' failed
pass: ./initialisation/global/struct.c
fail: ./initialisation/global/struct_addr.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_addr.c' failed
fail: ./initialisation/global/struct_fn.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_fn.c' failed
fail: ./initialisation/global/struct_offset.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_offset.c' failed
fail: ./initialisation/global/struct_pad.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_pad.c' failed
pass: ./initialisation/invalid/arrays.c
pass: ./initialisation/invalid/both.c
pass: ./initialisation/invalid/incomplete.c
pass: ./initialisation/invalid/incomplete_struct.c
pass: ./initialisation/scalar/brace.c
fail: ./initialisation/string/char_ar.c
  ./initialisation/string/char_ar.c:7:6: warning: initialisation type mismatch: char * <-- const char *
    "char *z = "yo";"
         ^
  ./initialisation/string/char_ar.c:7:6: warning: initialisation type mismatch: char * <-- const char *
    "char *z = "yo";"
         ^
  ./initialisation/string/char_ar.c:4:4: warning: control reaches end of non-void function main
    "main(){"
       ^
  ./initialisation/string/char_ar.c:7:6: warning: "z" never read
    "char *z = "yo";"
         ^
  /var/tmp/tmp.1.p9oh5F:37:FATAL:Symbol str.1 already defined.
  ../ucc: as returned 1
  ./test.pl: command '../ucc -c ./initialisation/string/char_ar.c -DPRE='main(){' -DPOST='}'' failed
fail: ./initialisation/struct/array_of.c
  ../ucc: cc1/cc1 caught signal 9
  ./test.pl: command '[ `../ucc ./initialisation/struct/array_of.c -S -o- | grep 'mov.*[1234]' | wc -l` -eq 4 ]' failed
fail: ./initialisation/struct/complicated.c
  TODO ./initialisation/struct/complicated.c
  ./test.pl: command 'false' failed
fail: ./initialisation/struct/nested_array_of_arrays.c
  ./initialisation/struct/nested_array_of_arrays.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/struct/nested_array_of_arrays.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./test.pl: command '[ `../ucc ./initialisation/struct/nested_array_of_arrays.c -S -o- | grep 'mov.*[123456789]' | wc -l` -eq 9 ]' failed
fail: ./initialisation/struct/nested_unbraced.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/struct/nested_unbraced.c' failed
fail: ./initialisation/struct/nesting.c
  ./initialisation/struct/nesting.c:18:16: warning: excess initialiser for struct
    "} a = { { 3 }, 2 };"
                   ^
  Died at ./asmcheck.pl line 6, <STDIN> line 9.
  ./test.pl: command '../ucc -DO='{' -DC='}' -S -o- ./initialisation/struct/nesting.c | ./asmcheck.pl ./initialisation/struct/nesting.c' failed
fail: ./initialisation/struct/pad.c
  ./initialisation/struct/pad.c:6:3: warning: initialisation type mismatch: int * <-- int
    "} a = { 0, 2 }, b = { 2, 3 };"
      ^
  ./initialisation/struct/pad.c:6:18: warning: initialisation type mismatch: int * <-- int
    "} a = { 0, 2 }, b = { 2, 3 };"
                     ^
  Died at ./asmcheck.pl line 6, <STDIN> line 15.
  ./test.pl: command '../ucc -S -o- ./initialisation/struct/pad.c | ./asmcheck.pl ./initialisation/struct/pad.c' failed
pass: ./initialisation/struct/simple.c
fail: ./initialisation/subobj_continue/array.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/array.c' failed
fail: ./initialisation/subobj_continue/array_aligns.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/array_aligns.c' failed
fail: ./initialisation/subobj_continue/array_error.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./initialisation/subobj_continue/array_error.c'...: No such file or directory
  ./test.pl: command '! ../ucc ./initialisation/subobj_continue/array_error.c' failed
fail: ./initialisation/subobj_continue/struct.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/struct.c' failed
fail: ./initialisation/subobj_continue/substruct.c
  Died at ./asmcheck.pl line 6.
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/substruct.c' failed
fail: ./initialisation/unbraced/limit.c
  ./initialisation/unbraced/limit.c:7:6: warning: initialisation type mismatch: int (*)[] <-- int (*)[2]
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:5:1: warning: control reaches end of non-void function a
    "a()"
    ^
  ./initialisation/unbraced/limit.c:16:1: warning: control reaches end of non-void function b
    "b()"
    ^
  ./initialisation/unbraced/limit.c:24:1: warning: control reaches end of non-void function c
    "c()"
    ^
  ./initialisation/unbraced/limit.c:7:6: warning: "p" never read
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:18:11: warning: "p" never read
    " struct A *p = (struct A []){"
              ^
  ./initialisation/unbraced/limit.c:7:6: warning: initialisation type mismatch: int (*)[] <-- int (*)[2]
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:5:1: warning: control reaches end of non-void function a
    "a()"
    ^
  ./initialisation/unbraced/limit.c:16:1: warning: control reaches end of non-void function b
    "b()"
    ^
  ./initialisation/unbraced/limit.c:24:1: warning: control reaches end of non-void function c
    "c()"
    ^
  ./initialisation/unbraced/limit.c:7:6: warning: "p" never read
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:18:11: warning: "p" never read
    " struct A *p = (struct A []){"
              ^
  ./initialisation/unbraced/limit.c:7:6: warning: initialisation type mismatch: int (*)[] <-- int (*)[2]
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:5:1: warning: control reaches end of non-void function a
    "a()"
    ^
  ./initialisation/unbraced/limit.c:16:1: warning: control reaches end of non-void function b
    "b()"
    ^
  ./initialisation/unbraced/limit.c:24:1: warning: control reaches end of non-void function c
    "c()"
    ^
  ./initialisation/unbraced/limit.c:7:6: warning: "p" never read
    " int (*p)[] = (int[][2]){ 1, 2, { 3, 4, 5 } };"
         ^
  ./initialisation/unbraced/limit.c:18:11: warning: "p" never read
    " struct A *p = (struct A []){"
              ^
  Died at ./asmcheck.pl line 6, <STDIN> line 57.
  ./test.pl: command '../ucc -S -o- ./initialisation/unbraced/limit.c | ./asmcheck.pl ./initialisation/unbraced/limit.c' failed
fail: ./initialisation/unbraced/multiple.c
  ./initialisation/unbraced/multiple.c:4:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./initialisation/unbraced/multiple.c:9:1: warning: control reaches end of non-void function g
    "g()"
    ^
  ./initialisation/unbraced/multiple.c:4:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./initialisation/unbraced/multiple.c:9:1: warning: control reaches end of non-void function g
    "g()"
    ^
  Usage: ./asmcheck.pl src
  ./test.pl: command '../ucc ./initialisation/unbraced/multiple.c -S -o- | ./asmcheck.pl' failed
pass: ./initialisation/zero_fill/array.c
fail: ./initialisation/zero_fill/multiple.c
  ./initialisation/zero_fill/multiple.c:4:1: warning: control reaches end of non-void function g
    "g()"
    ^
  ./initialisation/zero_fill/multiple.c:9:1: warning: control reaches end of non-void function h
    "h()"
    ^
  ./test.pl: command '[ `../ucc ./initialisation/zero_fill/multiple.c -S -o- | grep 'mov.*2' | wc -l` -eq 1 ]' failed
fail: ./initialisation/zero_fill/struct.c
  ./initialisation/zero_fill/struct.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/zero_fill/struct.c:21:23: warning: excess initialiser for struct
    " struct A b = { 1, 2, 3 };"
                          ^
  ./initialisation/zero_fill/struct.c:13:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./test.pl: command '[ `../ucc ./initialisation/zero_fill/struct.c -S -o- | grep 'mov.*0' | wc -l` -eq 1 ]' failed
fail: ./lib/select.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
fail: ./lib/sleep.c
  ./lib/sleep.c:2:1: error: can't find include file <stdlib.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc ./lib/sleep.c' failed
fail: ./lib/uname.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
fail: ./lib/usleep.c
  TODO
  ./test.pl: command 'echo TODO; false' failed
pass: ./lvalue/addr.c
pass: ./lvalue/func_addr.c
fail: ./lvalue/func_assign.c
  Can't exec "!../ucc": No such file or directory at ./timeout line 13.
  ./timeout: exec '!../ucc ./lvalue/func_assign.c'...: No such file or directory
  ./test.pl: command '!../ucc ./lvalue/func_assign.c' failed
fail: ./old_func/errors.c
  ./old_func/errors.c:3:6: error: no such parameter 'y'
    " int y;"
         ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./old_func/errors.c' failed
fail: ./old_func/works.c
  ./test.pl: undefined variable %ocheck in ./old_func/works.c
fail: ./other/__asm__.c
  ./other/__asm__.c:8:16: ICW parse.c:232 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./other/__asm__.c:9:27: error: expecting token comma, got identifier "EXIT_CODE" (parse.c:479)
    "                "movl $" EXIT_CODE ", %eax\n""
                              ^
  ./other/__asm__.c:12:9: error: expecting token comma, got string (parse.c:479)
    "        );"
            ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./other/__asm__.c' failed
fail: ./other/__file__.c
  ./other/__file__.c:6:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc -o ./__file__.out ./other/__file__.c' failed
fail: ./other/_Generic.c
  ./other/_Generic.c:13:7: warning: initialisation type mismatch: char * <-- const char *
    " char *s = "yo";"
          ^
  ./other/_Generic.c:15:17: warning: implicit declaration of function "printf"
    "  printf(_Generic(i, char *: "%s", int: "%d"), i);"
                    ^
  (null):20:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -o ./_Generic.out ./other/_Generic.c' failed
fail: ./other/_Generic_const.c
  (null):9:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  ./test.pl: command '../ucc -o ./_Generic_const.out ./other/_Generic_const.c' failed
pass: ./other/_Static_assert.c
pass: ./other/addr.c
fail: ./other/alphabet.c
  ./other/alphabet.c:4:1: error: can't find include file <stdlib.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc -o ./alphabet.out ./other/alphabet.c' failed
pass: ./other/ar_addr.c
pass: ./other/args_definitions.c
fail: ./other/array_addressof.c
  ./other/array_addressof.c:4:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc ./other/array_addressof.c -o ./array_addressof.out' failed
fail: ./other/array_size_check.c
  ./other/array_size_check.c:5:13: error: expecting token open_block, got comma (parse.c:779)
    "int printf(), abort();"
                ^
  ./other/array_size_check.c:5:13: error: expression expected, got comma (parse.c:239)
    "int printf(), abort();"
                ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -o ./array_size_check.out ./other/array_size_check.c' failed
fail: ./other/assert.c
  ./other/assert.c:5:1: error: can't find include file <assert.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc -o ./assert.out ./other/assert.c' failed
fail: ./other/assign_order.c
  ./other/assign_order.c:4:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc -fno-const-fold -o ./assign_order.out ./other/assign_order.c' failed
fail: ./other/atexit.c
  ./other/atexit.c:6:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  ./test.pl: command '../ucc -o ./atexit.out ./other/atexit.c' failed
fail: ./parse/empty_array.c
  ./parse/empty_array.c:2:21: error: dereference of pointer to incomplete type char (*([]))()
    "extern char (*(*x)[])();"
                        ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c -o ./empty_array.out ./parse/empty_array.c' failed
fail: ./parse/eof_mid_parse.c
  no error expected
  ./parse/eof_mid_parse.c:3:2: error: expecting token semicolon, got eof (parse_type.c:951)
    "a "
     ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./parse/eof_mid_parse.c' failed
pass: ./parse/expr_if.c
pass: ./parse/switch.c
fail: ./parse/type_storage.c
  no error expected
  ./parse/type_storage.c:5:15: error: storage unwanted (static)
    " return (static)5; "
                  ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./parse/type_storage.c' failed
fail: ./parsing/eof_mid.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./parsing/eof_mid.c'...: No such file or directory
  ./test.pl: command '! ../ucc ./parsing/eof_mid.c' failed
fail: ./parsing/parse_comma.c
  ./test.pl: undefined variable %ocheck in ./parsing/parse_comma.c
pass: ./parsing/tdef_func.c
pass: ./paths/reachable.c
pass: ./pointers/add.c
fail: ./pointers/func_arith.c
  check /warning: arithmetic on function pointer/ not found in warnings on line 5
  check /warning: arithmetic on function pointer/ not found in warnings on line 6
  ./test.pl: command './check.sh ./pointers/func_arith.c' failed
pass: ./pointers/ptr_cmp.c
fail: ./pointers/ptr_sub.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./pointers/ptr_sub.c'...: No such file or directory
  ./test.pl: command '! ../ucc ./pointers/ptr_sub.c' failed
fail: ./pointers/void_arith.c
  check /warning: arithmetic on void pointer/ not found in warnings on line 4
  ./test.pl: command './check.sh ./pointers/void_arith.c' failed
pass: ./random/confusion_parsing.c
fail: ./random/printf_args.c
  ./random/printf_args.c:6:11: warning: implicit declaration of function "printf"
    "  printf("argv[%d] = \"%s\"\n", i, argv[i]);"
              ^
  /var/tmp/tmp.1.pZTIRQ:66:FATAL:Symbol str.1 already defined.
  ../ucc: as returned 1
  ./test.pl: command '../ucc -o ./printf_args.out ./random/printf_args.c && ./printf_args.out hello | grep 'argv\[1\] = "hello"'' failed
fail: ./restrict/restrict_fine.c
  ./restrict/restrict_fine.c:6:20: error: externs can't be initialised
    " extern int i, *p, *q = (void *)0, *r;"
                       ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc ./restrict/restrict_fine.c -c' failed
pass: ./restrict/restrict_fptr.c
pass: ./restrict/restrict_int.c
pass: ./restrict/restrict_ptr_invalid.c
fail: ./restrict/restrict_undefined.c
  ./test.pl: undefined variable %c in ./restrict/restrict_undefined.c
pass: ./sign/cast.c
pass: ./sign/cmp.c
pass: ./sign/gen.c
pass: ./sign/rule.c
pass: ./simple/simple.c
pass: ./stack/clobber.c
fail: ./stack/packing.c
  ./test.pl: undefined variable %ocheck in ./stack/packing.c
fail: ./strings/basic.c
  ./strings/basic.c:14:7: warning: initialisation type mismatch: char * <-- const char *
    " char *s = "hi\n";"
          ^
  ./test.pl: undefined variable %ocheck in ./strings/basic.c
fail: ./strings/global.c
  ./test.pl: undefined variable %layoutcheck in ./strings/global.c
pass: ./structs/nested.c
pass: ./structs/nested_decl.c
fail: ./structs/offset_sizeof.c
  ./structs/offset_sizeof.c:42:13: warning: implicit declaration of function "printf"
    "  printf("(unsigned long)&((struct Y *)0)->i" " = %u\n", (unsigned long)&((struct Y *)0)->i);"
                ^
  ./structs/offset_sizeof.c:19:4: warning: control reaches end of non-void function main
    "main()"
       ^
  diff: ./structs/offset_sizeof.c.ocheck: No such file or directory
  ./test.pl: command './offset_sizeof.out | diff -u - ./structs/offset_sizeof.c.ocheck' failed
fail: ./structs/simple.c
  ./test.pl: command './simple.out' failed
pass: ./structs/validity.c
fail: ./structs/validity2.c
  ./structs/validity2.c:13:2: error: 'struct A *' (identifier-expr) is not a struct or union (member i)
    " p.i; "
     ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./structs/validity2.c:13:2: error: 'struct A *' (identifier-expr) is not a struct or union (member i)
    " p.i; "
     ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./structs/validity2.c' failed
fail: ./structs/validity3.c
  ./structs/validity3.c:13:2: error: 'struct A' (identifier-expr) is not a pointer to struct or union (member i)
    " a->i; "
     ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./structs/validity3.c:13:2: error: 'struct A' (identifier-expr) is not a pointer to struct or union (member i)
    " a->i; "
     ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./structs/validity3.c' failed
fail: ./switch/enum_int.c
  check /warning: not a member of enum/ not found in warnings on line 10
  ./test.pl: command './check.sh ./switch/enum_int.c' failed
fail: ./type_parsing_printing/func_ptr.c
  ./type_parsing_printing/func_ptr.c:13:4: warning: unused expression (op)
    " 1 - *g();"
       ^
  ./type_parsing_printing/func_ptr.c:14:4: warning: unused expression (op)
    " 1 - (*(*ptr_to_f_ret_ptr_to_f)())();"
       ^
  ./type_parsing_printing/func_ptr.c:15:4: warning: unused expression (op)
    " 1 - (*p)();"
       ^
  ./type_parsing_printing/func_ptr.c:16:4: warning: unused expression (op)
    " 1 - *(f());"
       ^
  ./type_parsing_printing/func_ptr.c:10:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Undefined symbols for architecture x86_64:
    "f", referenced from:
        main in tmp.2.smCoHr
       (maybe you meant: ptr_to_f_ret_ptr_to_f, fork , fdopendir , fflush , dirfd , printf , fopen , dprintf , fileno , fwrite , freopen , fputc , vprintf , fgetc , fprintf , fclose , fsetpos , ferror , fgets , fropen , fdopen , fputs , ftell , fgetpos , free , feof , funopen , fseek , fwopen , vfprintf , __assert_fail , fread )
    "g", referenced from:
        main in tmp.2.smCoHr
       (maybe you meant: isxdigit, __progname , isdigit , fgetc , __dump_regs , getchar , isgraph , fgets , getpid , fgetpos , getenv )
  ld: symbol(s) not found for inferred architecture x86_64
  ../ucc: ld returned 1
  ./test.pl: command '../ucc ./type_parsing_printing/func_ptr.c' failed
pass: ./type_parsing_printing/tdef_func.c
fail: ./type_parsing_printing/tdef_func_inst.c
  ./type_parsing_printing/tdef_func_inst.c:5:1: error: declaration doesn't declare anything
    "{"
    ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command '../ucc -c ./type_parsing_printing/tdef_func_inst.c' failed
fail: ./type_parsing_printing/tdef_test.c
  ./test.pl: undefined variable %layoutcheck in ./type_parsing_printing/tdef_test.c
fail: ./type_parsing_printing/type_ref_test.c
  ./test.pl: undefined variable %ocheck in ./type_parsing_printing/type_ref_test.c
pass: ./type_parsing_printing/typedef.c
pass: ./type_parsing_printing/typeof_nest.c
fail: ./type_parsing_printing/typeof_print.c
  ./type_parsing_printing/typeof_print.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never written to
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never read
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never written to
    " typeof(5)   b; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never read
    " typeof(5)   b; "
                 ^
      typeof(int) a (sym local, offset = 4)
  ./type_parsing_printing/typeof_print.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never written to
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never read
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never written to
    " typeof(5)   b; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never read
    " typeof(5)   b; "
                 ^
  ./test.pl: command '../ucc -Xprint ./type_parsing_printing/typeof_print.c | grep -F "typeof(expr: val) aka 'int' b"' failed
pass: ./type_parsing_printing/typeof_to_str.c
fail: ./type_parsing_printing/void_args_typedef.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc -DA -c ./type_parsing_printing/void_args_typedef.c'...: No such file or directory
  ./test.pl: command '! ../ucc -DA -c ./type_parsing_printing/void_args_typedef.c' failed
pass: ./type_propagation/compound_literal_typeof.c
pass: ./type_propagation/if_expr_fptr.c
fail: ./type_propagation/if_expr_void.c
  ./type_propagation/if_expr_void.c:6:20: error: dereference of pointer to incomplete type void
    " __typeof__(*(0 ? (int*)0 : (void*)1)) x; "
                       ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./type_propagation/if_expr_void.c:6:20: error: dereference of pointer to incomplete type void
    " __typeof__(*(0 ? (int*)0 : (void*)1)) x; "
                       ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./type_propagation/if_expr_void.c' failed
pass: ./typedef_typeof/tdef_ar.c
fail: ./warnings/pp.c
  no error expected
  ./warnings/pp.c:1:1: warning: #warning:  1 
  ./warnings/pp.c:6:1: warning: #warning:  6 
  ./warnings/pp.c:8:1: warning: #warning:  8 
  ./warnings/pp.c:10:1: warning: #warning:  10 
  ./warnings/pp.c:12:0: error: expecting token semicolon, got eof (parse_type.c:951)
    ""
   ^
  ../ucc: cc1/cc1 returned 1
  ./test.pl: command './check.sh ./warnings/pp.c' failed
fail: ./warnings/warn.c
  Usage: ./check.sh [-e] src
  -e: expect ucc to error
  ./test.pl: command './check.sh ./warnings/warn.c -Wall' failed
