pass: ./arrays/as_params/declarations.c
pass: ./arrays/as_params/static.c
pass: ./arrays/as_params/empty.c
pass: ./arrays/as_params/null_static.c
pass: ./arrays/as_params/restrict_ar.c
pass: ./arrays/opt_load.c
pass: ./arrays/stride_nx2x4.c
pass: ./arrays/op_order.c
pass: ./arrays/strlen_2.c
pass: ./arrays/bounds_parse.c
pass: ./arrays/ptr.c
pass: ./arrays/invalid_inc.c
pass: ./arrays/stride_nx3.c
pass: ./arrays/bounds_add.c
pass: ./arrays/bounds.c
pass: ./arrays/bounds_one_after.c
fail: ./initialisation/global/type_mismatch.c
  ./initialisation/global/type_mismatch.c:4:10: warning: mismatching types in initialisation (int * <-- int)
    "int *p = 5;"
             ^
  ./initialisation/global/type_mismatch.c:8:18: warning: mismatching types in initialisation (int * <-- int)
    " static int *p = 5;"
                     ^
  ./initialisation/global/type_mismatch.c:6:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./initialisation/global/type_mismatch.c:4:10: warning: mismatching types in initialisation (int * <-- int)
    "int *p = 5;"
             ^
  ./initialisation/global/type_mismatch.c:8:18: warning: mismatching types in initialisation (int * <-- int)
    " static int *p = 5;"
                     ^
  ./initialisation/global/type_mismatch.c:6:1: warning: control reaches end of non-void function f
    "f()"
    ^
  timeout: child returned 256
  ./test.pl: command '../ucc -S -o- ./initialisation/global/type_mismatch.c | grep -F '.long 5'' failed
fail: ./initialisation/global/struct_pad.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_pad.c' failed
pass: ./initialisation/global/compound_literal_addr_off.c
fail: ./initialisation/global/compound_lit_and_str.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/compound_lit_and_str.c' failed
fail: ./initialisation/global/static_addr.c
  ./initialisation/global/static_addr.c:8:18: error: static scalar initialiser not constant
    " static int *p = &a;"
                     ^
  ../ucc: cc1/cc1 returned 1
  ./initialisation/global/static_addr.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/global/static_addr.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  /tmp/file59SNr6: In function `main.static1_p':
  (.data+0x0): undefined reference to `a'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -DSTORE=extern ./initialisation/global/static_addr.c' failed
fail: ./initialisation/global/compound_literal.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/compound_literal.c' failed
fail: ./initialisation/global/array.c
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/global/array.c -S -o- | grep '[1234]' | wc -l` -eq 16 ]' failed
pass: ./initialisation/global/struct.c
fail: ./initialisation/global/designated_and_padding.c
  open ./initialisation/global/designated_and_padding.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/global/designated_and_padding.c' failed
fail: ./initialisation/global/empty.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/empty.c' failed
fail: ./initialisation/global/address_cast.c
  ./initialisation/global/address_cast.c:6:10: warning: mismatching types in initialisation (int * <-- int)
    "int *p = (int)&x; "
             ^
  ./initialisation/global/address_cast.c:6:10: error: global scalar initialiser not constant
    "int *p = (int)&x; "
             ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./initialisation/global/address_cast.c:6:10: warning: mismatching types in initialisation (int * <-- int)
    "int *p = (int)&x; "
             ^
  ./initialisation/global/address_cast.c:6:10: error: global scalar initialiser not constant
    "int *p = (int)&x; "
             ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./initialisation/global/address_cast.c' failed
pass: ./initialisation/global/array_init.c
fail: ./initialisation/global/cast.c
  open ./initialisation/global/cast.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/global/cast.c' failed
fail: ./initialisation/global/struct_fn.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_fn.c' failed
pass: ./initialisation/global/offsetof.c
pass: ./initialisation/global/global_negative.c
pass: ./initialisation/global/const_shortcircuit.c
fail: ./initialisation/global/globals.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/globals.c' failed
fail: ./initialisation/global/struct_addr.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_addr.c' failed
fail: ./initialisation/global/struct_offset.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/global/struct_offset.c' failed
fail: ./initialisation/compound_global/yes_no_cases.c
  TODO ./initialisation/compound_global/yes_no_cases.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_global/and_static.c
  TODO ./initialisation/compound_global/and_static.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_global/cast_lit.c
  ./initialisation/compound_global/cast_lit.c:3:9: error: global scalar initialiser not constant
    "int i = (int)(int){5};"
            ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -S -o- ./initialisation/compound_global/cast_lit.c | grep -E '\.long +5'' failed
fail: ./initialisation/compound_global/addr_global.c
  TODO ./initialisation/compound_global/addr_global.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/const_init.c
  ./initialisation/const_init.c:18:10: warning: implicit declaration of function "printf"
    " printf("%d {%d,%d,%d}, { {%d,%d,%s}, {%d,%d,%s}, {%d,%d,%s} }\n","
             ^
  ./initialisation/const_init.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './const_init.out | ./stdoutcheck.pl '5 {1,2,3}, { {1,2,hi}, {2,0,(null)}, {5,6,yo} }'' failed
fail: ./initialisation/unbraced/limit.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -c -o /dev/null ./initialisation/unbraced/limit.c' failed
fail: ./initialisation/unbraced/multiple.c
  ./initialisation/unbraced/multiple.c:4:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./initialisation/unbraced/multiple.c:9:1: warning: control reaches end of non-void function g
    "g()"
    ^
  ./initialisation/unbraced/multiple.c:4:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ./initialisation/unbraced/multiple.c:9:1: warning: control reaches end of non-void function g
    "g()"
    ^
  Usage: ./asmcheck.pl src
  timeout: child returned 65280
  ./test.pl: command '../ucc ./initialisation/unbraced/multiple.c -S -o- | ./asmcheck.pl' failed
fail: ./initialisation/unbraced/unbraced_toplvl.c
  open ./initialisation/unbraced/unbraced_toplvl.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/unbraced/unbraced_toplvl.c' failed
pass: ./initialisation/compound/funcall.c
pass: ./initialisation/compound/sizeof_parsing.c
fail: ./initialisation/compound/object.c
  ./initialisation/compound/object.c:8:6: warning: control reaches end of non-void function modify
    "modify(User *u)"
         ^
  ./initialisation/compound/object.c:15:10: warning: implicit declaration of function "printf"
    " printf("%s\n", u->name);"
             ^
  ./initialisation/compound/object.c:13:3: warning: control reaches end of non-void function run
    "run(User *u)"
      ^
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./object.out ./initialisation/compound/object.c' failed
fail: ./initialisation/compound/ptr.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/compound/ptr.c -S -o- | grep 'mov.*[1234]' | wc -l` -eq 4 ]' failed
fail: ./initialisation/compound/undefined.c
  TODO ./initialisation/compound/undefined.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/compound_lit/basic.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc ./initialisation/compound_lit/basic.c -o ./basic.out' failed
fail: ./initialisation/compound_lit/nested.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./nested.out ./initialisation/compound_lit/nested.c' failed
pass: ./initialisation/compound_lit/sizeof.c
pass: ./initialisation/scalar/brace.c
fail: ./initialisation/subobj_continue/array_error.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./initialisation/subobj_continue/array_error.c'...: No such file or directory
  timeout: child returned 32512
  ./test.pl: command '! ../ucc ./initialisation/subobj_continue/array_error.c' failed
fail: ./initialisation/subobj_continue/substruct.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/substruct.c' failed
fail: ./initialisation/subobj_continue/array.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/array.c' failed
fail: ./initialisation/subobj_continue/struct.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/struct.c' failed
fail: ./initialisation/subobj_continue/array_aligns.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/subobj_continue/array_aligns.c' failed
fail: ./initialisation/aggregate/copy.c
  ./initialisation/aggregate/copy.c:11:11: warning: implicit declaration of function "printf"
    "  printf("x[%d] = { %d, %d }\n","
              ^
  ./initialisation/aggregate/copy.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/aggregate/copy.c:13:1: ICE gen_asm.c:38 (lea_expr): invalid store expression addr (no f_store())
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./copy.out ./initialisation/aggregate/copy.c' failed
fail: ./initialisation/aggregate/large_copy.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./large_copy.out ./initialisation/aggregate/large_copy.c' failed
pass: ./initialisation/designated/enum_desig_index.c
fail: ./initialisation/designated/mixed_order_subobject.c
  open ./initialisation/designated/mixed_order_subobject.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/designated/mixed_order_subobject.c' failed
fail: ./initialisation/designated/aggregate_replacement/replace_subobj.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/aggregate_replacement/replace_subobj.c' failed
fail: ./initialisation/designated/all_3.c
  ./test.pl: undefined variable %layoutcheck in ./initialisation/designated/all_3.c
fail: ./initialisation/designated/desig_array_st.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/desig_array_st.c' failed
fail: ./initialisation/designated/unordered_struct.c
  check /warning: excess struct initialiser/ not found in warnings on line 13
  timeout: child returned 256
  ./test.pl: command './check.sh ./initialisation/designated/unordered_struct.c' failed
fail: ./initialisation/designated/backwards_struct.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/backwards_struct.c' failed
fail: ./initialisation/designated/array_nested_struct.c
  TODO ./initialisation/designated/array_nested_struct.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/designated/overwrite.c
  open ./initialisation/designated/overwrite.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/designated/overwrite.c' failed
fail: ./initialisation/designated/arrays.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/arrays.c' failed
fail: ./initialisation/designated/pass_through.c
  open ./initialisation/designated/pass_through.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/designated/pass_through.c' failed
fail: ./initialisation/designated/large_global.c
  open ./initialisation/designated/large_global.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/designated/large_global.c' failed
fail: ./initialisation/designated/array/array_range2.c
  ./initialisation/designated/array/array_range2.c:19:11: warning: implicit declaration of function "printf"
    "  printf("x[%d] = %d\n", i, x[i]);"
              ^
  ./initialisation/designated/array/array_range2.c:22:11: warning: implicit declaration of function "printf"
    "  printf("y[%d] = { %d, %d }\n", i, y[i].i, y[i].j);"
              ^
  ./initialisation/designated/array/array_range2.c:7:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/designated/array/array_range2.c:23:1: ICE gen_asm.c:38 (lea_expr): invalid store expression addr (no f_store())
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./array_range2.out ./initialisation/designated/array/array_range2.c' failed
fail: ./initialisation/designated/array/overwrite_array_range.c
  ./initialisation/designated/array/overwrite_array_range.c:18:11: warning: implicit declaration of function "printf"
    "  printf("x[%d] = { %d, %d, %d }\n","
              ^
  ./initialisation/designated/array/overwrite_array_range.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './overwrite_array_range.out | ./stdoutcheck.pl 'x\[0\] = { 1, 2, 3 }' 'x\[1\] = { 7, 5, 6 }' 'x\[2\] = { 7, 5, 6 }' 'x\[3\] = { 7, 5, 6 }'' failed
pass: ./initialisation/designated/array/basic.c
pass: ./initialisation/designated/array/continue_for_desig.c
fail: ./initialisation/designated/array/no_brace.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/array/no_brace.c' failed
fail: ./initialisation/designated/array/of_structs.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/array/of_structs.c' failed
fail: ./initialisation/designated/array/bounds.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./initialisation/designated/array/bounds.c'...: No such file or directory
  timeout: child returned 32512
  ./test.pl: command '! ../ucc ./initialisation/designated/array/bounds.c' failed
fail: ./initialisation/designated/struct/various_desig.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/designated/struct/various_desig.c' failed
pass: ./initialisation/designated/struct/sub_desig.c
fail: ./initialisation/union/local.c
  ./initialisation/union/local.c:23:10: warning: implicit declaration of function "printf"
    " printf("x = { .i = %d } :: { %d, %d, %d }\n","
             ^
  ./initialisation/union/local.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  Binary files - and ./initialisation/union/local.c.out differ
  timeout: child returned 512
  ./test.pl: command './local.out | diff -u - ./initialisation/union/local.c.out' failed
fail: ./initialisation/union/global.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/union/global.c' failed
fail: ./initialisation/union/size.c
  open ./initialisation/union/size.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/union/size.c' failed
fail: ./initialisation/zero_fill/multiple.c
  ./initialisation/zero_fill/multiple.c:4:1: warning: control reaches end of non-void function g
    "g()"
    ^
  ./initialisation/zero_fill/multiple.c:9:1: warning: control reaches end of non-void function h
    "h()"
    ^
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/zero_fill/multiple.c -S -o- | grep 'mov.*2' | wc -l` -eq 1 ]' failed
fail: ./initialisation/zero_fill/local_init.c
  ./../ucc: cc1/cc1 caught signal 11
  Died at ./retcheck.pl line 18.
  timeout: child returned 256
  ./test.pl: command './retcheck.pl 7 ./initialisation/zero_fill/local_init.c' failed
fail: ./initialisation/zero_fill/local_zero_12_byte_struct.c
  ./initialisation/zero_fill/local_zero_12_byte_struct.c:11:11: warning: implicit declaration of function "printf"
    "  printf("sts[%d] = { %d, %d, %d }\n","
              ^
  ./initialisation/zero_fill/local_zero_12_byte_struct.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './local_zero_12_byte_struct.out | ./stdoutcheck.pl 'sts\[0\] = { 0, 0, 0 }' 'sts\[1\] = { 0, 0, 0 }' 'sts\[2\] = { 0, 0, 0 }' 'sts\[3\] = { 0, 0, 0 }' 'sts\[4\] = { 0, 0, 0 }' 'sts\[5\] = { 0, 1, 0 }'' failed
pass: ./initialisation/zero_fill/array.c
fail: ./initialisation/zero_fill/struct.c
  ./initialisation/zero_fill/struct.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/zero_fill/struct.c:13:1: warning: control reaches end of non-void function f
    "f()"
    ^
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/zero_fill/struct.c -S -o- | grep 'mov.*0' | wc -l` -eq 1 ]' failed
pass: ./initialisation/zero_fill/local_init_zero.c
fail: ./initialisation/string/char_ar.c
  ./initialisation/string/char_ar.c:9:15: error: sizeof incomplete type char []
    "int q[sizeof x]; "
                  ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./initialisation/string/char_ar.c -DPRE= -DPOST=' failed
pass: ./initialisation/array/normal.c
pass: ./initialisation/array/nobrace.c
fail: ./initialisation/array/variations.c
  ./initialisation/array/variations.c:9:12: warning: implicit declaration of function "printf"
    "   printf("[%d][%d] = %d\n", i, j, a[i][j]);"
               ^
  ./initialisation/array/variations.c:4:1: warning: control reaches end of non-void function p
    "p(int (*a)[2])"
    ^
  ./initialisation/array/variations.c:12:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/array/variations.c:9:12: warning: implicit declaration of function "printf"
    "   printf("[%d][%d] = %d\n", i, j, a[i][j]);"
               ^
  ./initialisation/array/variations.c:4:1: warning: control reaches end of non-void function p
    "p(int (*a)[2])"
    ^
  ./initialisation/array/variations.c:12:4: warning: control reaches end of non-void function main
    "main()"
       ^
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/array/variations.c -S -o- | grep 'mov.*[0123]' | wc -l` -eq 12 ]' failed
fail: ./initialisation/array/char.c
  ./initialisation/array/char.c:4:15: error: char [] must be initialised with an initialiser list
    "char abc[] = "abc";"
                  ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./initialisation/array/char.c -c' failed
pass: ./initialisation/array/brace.c
fail: ./initialisation/struct/nesting.c
  Died at ./asmcheck.pl line 6, <STDIN> line 9.
  timeout: child returned 512
  ./test.pl: command '../ucc -DO='{' -DC='}' -S -o- ./initialisation/struct/nesting.c | ./asmcheck.pl ./initialisation/struct/nesting.c' failed
fail: ./initialisation/struct/nested_array_of_arrays.c
  ./initialisation/struct/nested_array_of_arrays.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./initialisation/struct/nested_array_of_arrays.c:5:4: warning: control reaches end of non-void function main
    "main()"
       ^
  timeout: child returned 256
  ./test.pl: command '[ `../ucc ./initialisation/struct/nested_array_of_arrays.c -S -o- | grep 'mov.*[123456789]' | wc -l` -eq 9 ]' failed
pass: ./initialisation/struct/copy.c
pass: ./initialisation/struct/array_of.c
fail: ./initialisation/struct/empty/warn_missing_empty.c
  open ./initialisation/struct/empty/warn_missing_empty.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/struct/empty/warn_missing_empty.c' failed
fail: ./initialisation/struct/empty/empty_first_union.c
  open ./initialisation/struct/empty/empty_first_union.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/struct/empty/empty_first_union.c' failed
fail: ./initialisation/struct/empty/empty.c
  ./initialisation/struct/empty/empty.c:6:1: warning: empty struct
    "};"
    ^
  ./initialisation/struct/empty/empty.c:26:11: warning: implicit declaration of function "_printf"
    " _printf("%d %d %d %d\n","
              ^
  ./initialisation/struct/empty/empty.c:20:5: warning: control reaches end of non-void function _main
    "_main()"
        ^
  ..//src/ucc//../../lib/crt.o: In function `_start':
  (.text+0x29): undefined reference to `main'
  /tmp/fileWOdORD: In function `_main':
  (.text+0x2e): undefined reference to `_printf'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./empty.out ./initialisation/struct/empty/empty.c' failed
fail: ./initialisation/struct/empty/empty_notfirst_union.c
  open ./initialisation/struct/empty/empty_notfirst_union.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/struct/empty/empty_notfirst_union.c' failed
fail: ./initialisation/struct/empty/init.c
  open ./initialisation/struct/empty/init.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/struct/empty/init.c' failed
fail: ./initialisation/struct/pad.c
  ./initialisation/struct/pad.c:6:9: warning: mismatching types in initialisation (int * <-- int)
    "} a = { 0, 2 }, b = { 2, 3 };"
            ^
  ./initialisation/struct/pad.c:6:23: warning: mismatching types in initialisation (int * <-- int)
    "} a = { 0, 2 }, b = { 2, 3 };"
                          ^
  Died at ./asmcheck.pl line 6, <STDIN> line 15.
  timeout: child returned 512
  ./test.pl: command '../ucc -S -o- ./initialisation/struct/pad.c | ./asmcheck.pl ./initialisation/struct/pad.c' failed
pass: ./initialisation/struct/simple.c
fail: ./initialisation/struct/nested_unbraced.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./initialisation/struct/nested_unbraced.c' failed
fail: ./initialisation/struct/complicated.c
  TODO ./initialisation/struct/complicated.c
  timeout: child returned 256
  ./test.pl: command 'false' failed
fail: ./initialisation/invalid/both.c
  ./initialisation/invalid/both.c:5:11: error: int [] must be initialised with an initialiser list
    "int x[] = 1;"
              ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c      ./initialisation/invalid/both.c; [ $? -ne 0 ]' failed
fail: ./initialisation/invalid/incomplete_array_struct.c
  open ./initialisation/invalid/incomplete_array_struct.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./initialisation/invalid/incomplete_array_struct.c' failed
pass: ./initialisation/invalid/arrays.c
pass: ./initialisation/invalid/incomplete.c
pass: ./initialisation/invalid/incomplete_struct.c
fail: ./wchar/str.c
  ./wchar/str.c:4:1: error: can't find include file <wchar.h>
  ./../ucc: cpp2/cpp returned 1
  Died at ./retcheck.pl line 18.
  timeout: child returned 256
  ./test.pl: command './retcheck.pl 66 ./wchar/str.c' failed
fail: ./wchar/char.c
  ./wchar/char.c:2:1: error: can't find include file <wchar.h>
  ./../ucc: cpp2/cpp returned 1
  Died at ./retcheck.pl line 18.
  timeout: child returned 256
  ./test.pl: command './retcheck.pl 97 ./wchar/char.c' failed
pass: ./wchar/type.c
pass: ./pointers/void_arith.c
fail: ./pointers/int_cmp.c
  ./pointers/int_cmp.c:6:12: warning: comparison between pointer and integer (int vs int *)
    " return 2 == i; "
               ^
  /tmp/fileRO7Ye5: In function `main':
  (.text+0x7): undefined reference to `i'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./pointers/int_cmp.c' failed
pass: ./pointers/ptr_cmp.c
fail: ./pointers/ptr_sub.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc ./pointers/ptr_sub.c'...: No such file or directory
  timeout: child returned 32512
  ./test.pl: command '! ../ucc ./pointers/ptr_sub.c' failed
fail: ./pointers/func_arith.c
  check /warning: arithmetic on function pointer/ not found in warnings on line 5
  check /warning: arithmetic on function pointer/ not found in warnings on line 6
  timeout: child returned 256
  ./test.pl: command './check.sh ./pointers/func_arith.c' failed
pass: ./pointers/add.c
fail: ./lib/uname.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
fail: ./lib/usleep.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
fail: ./lib/select.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
fail: ./lib/sleep.c
  ./lib/sleep.c:2:1: error: can't find include file <stdlib.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./lib/sleep.c' failed
pass: ./casts/invalid.c
pass: ./casts/bool.c
pass: ./casts/invalid_bool.c
pass: ./casts/ineq_ptr.c
pass: ./casts/const_cast.c
fail: ./cpp/overload.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
pass: ./cpp/count_params.c
pass: ./cpp/cpp.c
fail: ./clang/ptr-arith.c
  ./test.pl: undefined variable %clang_cc in ./clang/ptr-arith.c
fail: ./clang/expressions.c
  ./test.pl: undefined variable %clang_cc in ./clang/expressions.c
fail: ./clang/declarators.c
  ./test.pl: undefined variable %clang_cc in ./clang/declarators.c
fail: ./clang/if-scope.c
  ./test.pl: undefined variable %clang_cc in ./clang/if-scope.c
fail: ./clang/switch.c
  ./test.pl: undefined variable %clang_cc in ./clang/switch.c
fail: ./clang/typeof.c
  ./test.pl: undefined variable %clang_cc in ./clang/typeof.c
fail: ./clang/ptr-promote.c
  ./test.pl: undefined variable %clang_cc in ./clang/ptr-promote.c
fail: ./clang/stmts.c
  ./test.pl: undefined variable %clang_cc in ./clang/stmts.c
fail: ./clang/types.c
  ./test.pl: undefined variable %clang_cc in ./clang/types.c
fail: ./clang/proto-promote.c
  ./test.pl: undefined variable %clang_cc in ./clang/proto-promote.c
pass: ./lvalue/func_assign.c
pass: ./lvalue/addr.c
pass: ./lvalue/func_addr.c
pass: ./typedef/scoping.c
fail: ./typedef/scoping2.c
  check /error: second type "size_t" specified after primitive/ not found in warnings on line 3
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./typedef/scoping2.c' failed
fail: ./typedef/scoping3.c
  check /error: redefinition of size_t from:/ not found in warnings on line 3
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./typedef/scoping3.c' failed
fail: ./typedef/tdef.c
  no error expected
  ../ucc: unrecognised option "-e"
  timeout: child returned 256
  ./test.pl: command './check.sh -DCLASH -e ./typedef/tdef.c' failed
fail: ./typedef/shadow.c
  error expected
  ./typedef/shadow.c:9:13: warning: mismatching types in initialisation (size_t (aka 'void *')  <-- int)
    " size_t p = 5;"
                ^
  ./typedef/shadow.c:11:9: warning: mismatching return type for main (int <-- size_t (aka 'void *') )
    " return p;"
            ^
  ./typedef/shadow.c:7:15: warning: "size_t" never read
    " typedef void *size_t; "
                  ^
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./typedef/shadow.c' failed
fail: ./switch/enum_int.c
  check /warning: enum ::A not handled in switch/ not found in warnings on line 9
  check /warning: not a member of enum/ not found in warnings on line 10
  timeout: child returned 256
  ./test.pl: command './check.sh ./switch/enum_int.c' failed
pass: ./compound_literal/adv_addr.c
pass: ./compound_literal/global.c
pass: ./compound_literal/nested_several.c
fail: ./compound_literal/addr.c
  ./compound_literal/addr.c:8:1: ICE sym.c:89 (symtab_search): symtab_search() with NULL spel
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./addr.out ./compound_literal/addr.c' failed
pass: ./compound_literal/sizeof.c
fail: ./compound_literal/c-lit.c
  ./compound_literal/c-lit.c:13:1: ICE sym.c:89 (symtab_search): symtab_search() with NULL spel
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./c-lit.out ./compound_literal/c-lit.c' failed
pass: ./compound_literal/add.c
pass: ./compound_literal/ptr.c
pass: ./builtin/expect.c
pass: ./builtin/all.c
pass: ./builtin/propagation.c
pass: ./builtin/unused.c
pass: ./builtin/sizeof.c
fail: ./builtin/frame_address.c
  ./builtin/frame_address.c:8:10: warning: implicit declaration of function "printf"
    " printf("%d\n", i);"
             ^
  ./builtin/frame_address.c:8:12: warning: "i" uninitialised on read
    " printf("%d\n", i);"
               ^
  ./builtin/frame_address.c:3:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './frame_address.out | ./stdoutcheck.pl '^3$'' failed
pass: ./ucc/if_scope.c
pass: ./registers/nospace.c
pass: ./__attribute__/reachability.c
pass: ./__attribute__/nonnull_simple.c
pass: ./__attribute__/enum_bitmask.c
pass: ./__attribute__/prototypes.c
pass: ./__attribute__/underscore.c
pass: ./__attribute__/awkward.c
pass: ./__attribute__/_Noreturn.c
pass: ./__attribute__/sentinel.c
pass: ./__attribute__/nonnull.c
pass: ./__attribute__/attr_simple.c
pass: ./typedef_typeof/tdef_ar.c
pass: ./typedef_typeof/simple.c
pass: ./const/const_int.c
fail: ./type_propagation/if_expr_void.c
  ./type_propagation/if_expr_void.c:8:4: warning: implicit declaration of function "f"
    " f(*x);"
       ^
  ./type_propagation/if_expr_void.c:8:5: warning: "x" uninitialised on read
    " f(*x);"
        ^
  ./type_propagation/if_expr_void.c:6:40: error: invalid indirection applied to int
    " __typeof__(*(0 ? (int*)0 : (void*)1)) x; "
                                           ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./type_propagation/if_expr_void.c:8:4: warning: implicit declaration of function "f"
    " f(*x);"
       ^
  ./type_propagation/if_expr_void.c:8:5: warning: "x" uninitialised on read
    " f(*x);"
        ^
  ./type_propagation/if_expr_void.c:6:40: error: invalid indirection applied to int
    " __typeof__(*(0 ? (int*)0 : (void*)1)) x; "
                                           ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./type_propagation/if_expr_void.c' failed
fail: ./type_propagation/if_expr_fptr.c
  ./type_propagation/if_expr_fptr.c:5:2: warning: "x" uninitialised on read
    " x();"
     ^
  ./type_propagation/if_expr_fptr.c:5:2: error: identifier-expression (type 'int') not callable
    " x();"
     ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./type_propagation/if_expr_fptr.c' failed
fail: ./type_propagation/compound_literal_typeof.c
  ./type_propagation/compound_literal_typeof.c:8:16: warning: "a" uninitialised on read
    " return sizeof a;"
                   ^
  timeout: child returned 256
  ./test.pl: command './compound_literal_typeof.out; [ $? -eq 12 ]' failed
fail: ./assignment/assign_check.c
  ./assignment/assign_check.c:15:15: warning: assignment type mismatch: struct A *((*)(int)) <-- struct A *((*)(int i, int j))
    "  a.f = ret_me; "
                  ^
  ./assignment/assign_check.c:18:10: warning: implicit declaration of function "printf"
    " printf("%d\n", i);"
             ^
  ./assignment/assign_check.c:8:22: warning: "j" never read
    "} *ret_me(int i, int j)"
                         ^
  timeout: child returned 136
  ./test.pl: command './assign_check.out' failed
pass: ./assignment/valid1.c
pass: ./enum/enum.c
pass: ./code_gen/vtop_check.c
pass: ./stack/register.c
pass: ./stack/clobber.c
pass: ./stack/packing.c
fail: ./std/for_init.c
  ./std/for_init.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  timeout: child returned 256
  ./test.pl: command '../ucc ./std/for_init.c 2>&1 | grep .; [ $? -ne 0 ]' failed
fail: ./std/trailing.c
  ./check.pl: open '-std=c89': No such file or directory
  timeout: child returned 512
  ./test.pl: command './check.sh -std=c89 ./std/trailing.c' failed
fail: ./std/if_decl.c
  ./std/if_decl.c:3:4: warning: control reaches end of non-void function main
    "main()"
       ^
  cc1: pack.c:8: pack_to_align: Assertion `align > 0' failed.
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc ./std/if_decl.c' failed
pass: ./std/C99_block_scope_2.c
pass: ./std/C99_block_scope.c
pass: ./std/scope_fail.c
pass: ./simple/simple.c
fail: ./random/printf_args.c
  ./random/printf_args.c:6:11: warning: implicit declaration of function "printf"
    "  printf("argv[%d] = \"%s\"\n", i, argv[i]);"
              ^
  Floating point exception (core dumped)
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./printf_args.out ./random/printf_args.c && ./printf_args.out hello | grep 'argv\[1\] = "hello"'' failed
pass: ./random/confusion_parsing.c
pass: ./structs/validity.c
pass: ./structs/copy.c
fail: ./structs/validity2.c
  ./structs/validity2.c:13:2: error: 'struct A *' (identifier-expr) is not a struct or union (member i)
    " p.i; "
     ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./structs/validity2.c:13:2: error: 'struct A *' (identifier-expr) is not a struct or union (member i)
    " p.i; "
     ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./structs/validity2.c' failed
fail: ./structs/anon/Plan9/oo.c
  ./structs/anon/Plan9/oo.c:21:9: error: declaration doesn't declare anything
    "  Animal;"
            ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -fplan9-extensions -o ./oo.out ./structs/anon/Plan9/oo.c' failed
fail: ./structs/anon/Plan9/p9_2.c
  ./structs/anon/Plan9/p9_2.c:11:3: error: declaration doesn't declare anything
    " B;"
      ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./p9_2.out ./structs/anon/Plan9/p9_2.c' failed
fail: ./structs/anon/Plan9/all.c
  ./structs/anon/Plan9/all.c:24:6: error: declaration doesn't declare anything
    " Lock;"
         ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -fplan9-extensions -o ./all.out ./structs/anon/Plan9/all.c' failed
fail: ./structs/anon/Plan9/p9_1.c
  ./structs/anon/Plan9/p9_1.c:6:34: error: expecting token semicolon, got close_block (parse.c:958)
    "f(struct A *p){p->a = 1, p->b = 2}"
                                     ^
  ./../ucc: cc1/cc1 returned 1
  Died at ./retcheck.pl line 18.
  timeout: child returned 256
  ./test.pl: command './retcheck.pl 4 ./structs/anon/Plan9/p9_1.c' failed
fail: ./structs/anon/so.c
  open ./structs/anon/so.c.layout: No such file or directory
  timeout: child returned 512
  ./test.pl: command './layout_check.sh ./structs/anon/so.c' failed
pass: ./structs/anon/basic.c
pass: ./structs/anon/nested.c
fail: ./structs/anon/all.c
  ./structs/anon/all.c:62:3: error: declaration doesn't declare anything
    " U;"
      ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./structs/anon/all.c' failed
pass: ./structs/anon/fopt/C11.c
fail: ./structs/anon/fopt/p9.c
  ./structs/anon/fopt/p9.c:12:6: error: declaration doesn't declare anything
    " Name;"
         ^
  ../ucc: cc1/cc1 returned 1
  ./structs/anon/fopt/p9.c:12:6: error: declaration doesn't declare anything
    " Name;"
         ^
  ../ucc: cc1/cc1 returned 1
  ./structs/anon/fopt/p9.c:12:6: error: declaration doesn't declare anything
    " Name;"
         ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -fplan9-extensions -c ./structs/anon/fopt/p9.c' failed
pass: ./structs/anon/fopt/ms.c
pass: ./structs/anon/simple.c
fail: ./structs/anon/anon.c
  ./structs/anon/anon.c:11:1: warning: control reaches end of non-void function q
    "q()"
    ^
  ./structs/anon/anon.c:31:1: warning: control reaches end of non-void function f
    "f()"
    ^
  ..//src/ucc//../../lib/crt.o: In function `_start':
  (.text+0x29): undefined reference to `main'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./structs/anon/anon.c' failed
pass: ./structs/anon/dup.c
pass: ./structs/nested.c
fail: ./structs/nested_decl.c
  ./structs/nested_decl.c:4:13: error: nested struct
    " struct node;"
                ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./structs/nested_decl.c' failed
fail: ./structs/simple.c
  timeout: child returned 256
  ./test.pl: command './simple.out' failed
pass: ./structs/scope/nested.c
fail: ./structs/offset_sizeof.c
  ./structs/offset_sizeof.c:42:13: warning: implicit declaration of function "printf"
    "  printf("(unsigned long)&((struct Y *)0)->i" " = %u\n", (unsigned long)&((struct Y *)0)->i);"
                ^
  ./structs/offset_sizeof.c:19:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  diff: ./structs/offset_sizeof.c.ocheck: No such file or directory
  timeout: child returned 512
  ./test.pl: command './offset_sizeof.out | diff -u - ./structs/offset_sizeof.c.ocheck' failed
fail: ./structs/validity3.c
  ./structs/validity3.c:13:2: error: 'struct A' (identifier-expr) is not a pointer to struct or union (member i)
    " a->i; "
     ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./structs/validity3.c:13:2: error: 'struct A' (identifier-expr) is not a pointer to struct or union (member i)
    " a->i; "
     ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./structs/validity3.c' failed
fail: ./blocks/deep.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./blocks/deep.c' failed
fail: ./blocks/blocks_simple.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./blocks_simple.out ./blocks/blocks_simple.c' failed
fail: ./blocks/basic.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./basic.out ./blocks/basic.c' failed
fail: ./blocks/folding.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./folding.out ./blocks/folding.c' failed
fail: ./blocks/block_ret.c
  ./blocks/block_ret.c:8:40: warning: implicit declaration of function "printf"
    " int (^f)(int) = ^int (int i) {printf("hi %d\n", i); return 0;};"
                                           ^
  ./blocks/block_ret.c:8:42: error: undeclared identifier "i"
    " int (^f)(int) = ^int (int i) {printf("hi %d\n", i); return 0;};"
                                             ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./block_ret.out ./blocks/block_ret.c' failed
fail: ./blocks/block_const.c
  check /error: .*const/ not found in warnings on line 8
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./blocks/block_const.c' failed
fail: ./blocks/blocks_args.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./blocks_args.out ./blocks/blocks_args.c' failed
fail: ./blocks/equal.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./equal.out ./blocks/equal.c' failed
fail: ./blocks/nest.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./nest.out ./blocks/nest.c' failed
fail: ./blocks/blocks_state.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./blocks_state.out ./blocks/blocks_state.c' failed
fail: ./blocks/block_decl.c
  ./blocks/block_decl.c:4:16: error: function argument 1 is static or extern
    "int dispatch(int(char));"
                   ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./block_decl.out ./blocks/block_decl.c' failed
fail: ./blocks/full_decl.c
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./full_decl.out ./blocks/full_decl.c' failed
pass: ./anywhere_decl/decl.c
pass: ./anywhere_decl/parse.c
fail: ./anywhere_decl/loop.c
  ./anywhere_decl/loop.c:4:1: warning: control reaches end of non-void function x
    "x(){}"
    ^
  ./anywhere_decl/loop.c:13:11: warning: implicit declaration of function "printf"
    "  printf("%d, %d\n", i, j);"
              ^
  ./anywhere_decl/loop.c:14:3: warning: unused expression (identifier)
    "  j;"
      ^
  ./anywhere_decl/loop.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './loop.out | ./stdoutcheck.pl '0, 3' '1, 3' '2, 3' '3, 3' '4, 3'' failed
fail: ./anywhere_decl/shadow.c
  check /error: "i" already declared/ not found in warnings on line 9
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./anywhere_decl/shadow.c' failed
pass: ./type_parsing_printing/tdef_func.c
fail: ./type_parsing_printing/void_args_typedef.c
  Can't exec "!": No such file or directory at ./timeout line 13.
  ./timeout: exec '! ../ucc -DA -c ./type_parsing_printing/void_args_typedef.c'...: No such file or directory
  timeout: child returned 32512
  ./test.pl: command '! ../ucc -DA -c ./type_parsing_printing/void_args_typedef.c' failed
pass: ./type_parsing_printing/type_ref_test.c
fail: ./type_parsing_printing/typeof_print.c
  ./type_parsing_printing/typeof_print.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never written to
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:6:14: warning: "a" never read
    " typeof(int) a; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never written to
    " typeof(5)   b; "
                 ^
  ./type_parsing_printing/typeof_print.c:7:14: warning: "b" never read
    " typeof(5)   b; "
                 ^
  timeout: child returned 256
  ./test.pl: command '../ucc -Xprint ./type_parsing_printing/typeof_print.c | grep -F "typeof(int) a"' failed
fail: ./type_parsing_printing/tdef_test.c
  ./test.pl: undefined variable %layoutcheck in ./type_parsing_printing/tdef_test.c
pass: ./type_parsing_printing/typedef.c
fail: ./type_parsing_printing/tdef_func_inst.c
  ./type_parsing_printing/tdef_func_inst.c:5:1: error: declaration doesn't declare anything
    "{"
    ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./type_parsing_printing/tdef_func_inst.c' failed
fail: ./type_parsing_printing/typeof_to_str.c
  timeout: child returned 256
  ./test.pl: command '../ucc -Xprint ./type_parsing_printing/typeof_to_str.c | grep -F 'typeof(typeof(size_t)) a'' failed
fail: ./type_parsing_printing/func_ptr.c
  ./type_parsing_printing/func_ptr.c:13:4: warning: unused expression (op)
    " 1 - *g();"
       ^
  ./type_parsing_printing/func_ptr.c:14:4: warning: unused expression (op)
    " 1 - (*(*ptr_to_f_ret_ptr_to_f)())();"
       ^
  ./type_parsing_printing/func_ptr.c:15:4: warning: unused expression (op)
    " 1 - (*p)();"
       ^
  ./type_parsing_printing/func_ptr.c:16:4: warning: unused expression (op)
    " 1 - *(f());"
       ^
  ./type_parsing_printing/func_ptr.c:10:4: warning: control reaches end of non-void function main
    "main()"
       ^
  /tmp/fileXr1bT4: In function `main':
  (.text+0x7): undefined reference to `g'
  /tmp/fileXr1bT4: In function `main':
  (.text+0x37): undefined reference to `f'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./type_parsing_printing/func_ptr.c' failed
pass: ./type_parsing_printing/typeof_nest.c
fail: ./parsing/tdef_func.c
  ./parsing/tdef_func.c:5:1: error: expecting token semicolon, got open_block (parse_type.c:1098)
    "{"
    ^
  ./parsing/tdef_func.c:5:1: error: expecting token eof, got open_block (parse.c:1021)
    "{"
    ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./parsing/tdef_func.c' failed
pass: ./parsing/eof_mid.c
pass: ./parsing/binary_precedence.c
fail: ./parsing/empty_array.c
  ./parsing/empty_array.c:3:5: error: incomplete array size attempt
    "int x[]; "
        ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./parsing/empty_array.c' failed
pass: ./parsing/numbers.c
pass: ./parsing/parse_comma.c
pass: ./parsing/logical_precedence.c
fail: ./parsing/vla_ar.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
pass: ./parse/eof_mid_parse.c
pass: ./parse/switch.c
pass: ./parse/expr_if.c
pass: ./parse/empty.c
pass: ./parse/empty_array.c
pass: ./parse/type_storage.c
pass: ./functions/stret.c
pass: ./functions/implicitly_void.c
fail: ./strings/basic.c
  ./strings/basic.c:7:14: error: char [] must be initialised with an initialiser list
    " char s[] = "hello";"
                 ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./basic.out ./strings/basic.c' failed
fail: ./strings/global.c
  ./test.pl: undefined variable %layoutcheck in ./strings/global.c
pass: ./old_func/errors.c
pass: ./old_func/works.c
fail: ./warnings/pp.c
  no error expected
  ./warnings/pp.c:1:1: warning: #warning:  1 
  ./warnings/pp.c:6:1: warning: #warning:  6 
  ./warnings/pp.c:8:1: warning: #warning:  8 
  ./warnings/pp.c:10:1: warning: #warning:  10 
  ./warnings/pp.c:12:0: error: expecting token semicolon, got eof (parse_type.c:1098)
    ""
   ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./warnings/pp.c' failed
fail: ./warnings/warn.c
  no error expected
  ./warnings/warn.c:5:1: warning: #warning:  hello 
  ./warnings/warn.c:9:1: warning: #warning:  timmy 
  ./warnings/warn.c:6:9: warning: mismatching return type for main (int <-- void *)
    " return (void *)5; "
            ^
  ./warnings/warn.c:11:1: warning: control reaches end of non-void function f
    "f()"
    ^
  Assembler messages:
  Error: can't open l for reading: No such file or directory
  ../ucc: as returned 1
  timeout: child returned 256
  ./test.pl: command './check.sh ./warnings/warn.c -Wall' failed
pass: ./sign/rule.c
pass: ./sign/cast.c
pass: ./sign/gen.c
pass: ./sign/cmp.c
pass: ./calcs/const_address.c
pass: ./calcs/struct.c
pass: ./restrict/restrict_undefined.c
fail: ./restrict/restrict_fine.c
  ./restrict/restrict_fine.c:6:20: error: externs can't be initialised
    " extern int i, *p, *q = (void *)0, *r;"
                       ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./restrict/restrict_fine.c -c' failed
pass: ./restrict/restrict_fptr.c
pass: ./restrict/restrict_int.c
pass: ./restrict/restrict_ptr_invalid.c
pass: ./driver/output-fail.c
pass: ./decl_parsing/ar.c
pass: ./decl_parsing/add_or_sub.c
pass: ./decl_parsing/fptr_arg.c
fail: ./decl_parsing/fptr.c
  ./decl_parsing/fptr.c:6:10: warning: implicit declaration of function "printf"
    " printf("inst(%d)\n", i);"
             ^
  ./decl_parsing/fptr.c:20:4: warning: unused expression (deref)
    " *f;"
       ^
  ./decl_parsing/fptr.c:9:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './fptr.out | ./stdoutcheck.pl 1 2 3 4 5 7 3 3' failed
fail: ./decl_parsing/fptr_get.c
  ./decl_parsing/fptr_get.c:5:10: warning: implicit declaration of function "printf"
    " printf("yo\n");"
             ^
  ./decl_parsing/fptr_get.c:3:5: warning: control reaches end of non-void function x
    "int x()"
        ^
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './fptr_get.out | ./stdoutcheck.pl yo' failed
fail: ./decl_parsing/st_fn.c
  ./decl_parsing/st_fn.c:5:14: warning: implicit declaration of function "printf"
    "p1(){printf("yo\n");}"
                 ^
  ./decl_parsing/st_fn.c:5:2: warning: control reaches end of non-void function p1
    "p1(){printf("yo\n");}"
     ^
  ./decl_parsing/st_fn.c:15:10: warning: assignment type mismatch: void (*)(void) <-- int (*)()
    " f.f = p1;"
             ^
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './st_fn.out | ./stdoutcheck.pl yo' failed
pass: ./decl_parsing/arg.c
pass: ./decl_parsing/simple.c
pass: ./decl_parsing/parse_test.c
pass: ./decl_parsing/ptr.c
fail: ./decl_parsing/atexit/atexit2.c
  ./decl_parsing/atexit/atexit2.c:6:3: warning: control reaches end of non-void function add
    "add(int (*f)())"
      ^
  ./decl_parsing/atexit/atexit2.c:11:3: warning: control reaches end of non-void function run
    "run()"
      ^
  ./decl_parsing/atexit/atexit2.c:17:13: warning: implicit declaration of function "printf"
    "a(){printf("a\n");}"
                ^
  ./decl_parsing/atexit/atexit2.c:17:1: warning: control reaches end of non-void function a
    "a(){printf("a\n");}"
    ^
  ./decl_parsing/atexit/atexit2.c:18:13: warning: implicit declaration of function "printf"
    "b(){printf("b\n");}"
                ^
  ./decl_parsing/atexit/atexit2.c:18:1: warning: control reaches end of non-void function b
    "b(){printf("b\n");}"
    ^
  ./decl_parsing/atexit/atexit2.c:20:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './atexit2.out | ./stdoutcheck.pl a b' failed
fail: ./decl_parsing/atexit/atexit_simplified.c
  ./decl_parsing/atexit/atexit_simplified.c:7:3: warning: control reaches end of non-void function add
    "add(void (*f)())"
      ^
  ./decl_parsing/atexit/atexit_simplified.c:15:10: warning: implicit declaration of function "printf"
    " printf("fs = %p\n", fs);"
             ^
  ./decl_parsing/atexit/atexit_simplified.c:12:3: warning: control reaches end of non-void function run
    "run()"
      ^
  ./decl_parsing/atexit/atexit_simplified.c:22:21: warning: implicit declaration of function "printf"
    " void a(){printf("a" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:23:21: warning: implicit declaration of function "printf"
    " void b(){printf("b" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:24:21: warning: implicit declaration of function "printf"
    " void c(){printf("c" "\n");}"
                        ^
  ./decl_parsing/atexit/atexit_simplified.c:26:4: warning: control reaches end of non-void function main
    "main()"
       ^
  /tmp/fileAXPTHw: Assembler messages:
  /tmp/fileAXPTHw:127: Error: symbol `str.1' is already defined
  ../ucc: as returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./atexit_simplified.out ./decl_parsing/atexit/atexit_simplified.c' failed
fail: ./decl_parsing/atexit/atexit.c
  ./decl_parsing/atexit/atexit.c:5:10: warning: implicit declaration of function "printf"
    " printf("beet\n");"
             ^
  ./decl_parsing/atexit/atexit.c:3:4: warning: control reaches end of non-void function p_hi
    "p_hi()"
       ^
  ./decl_parsing/atexit/atexit.c:10:10: warning: implicit declaration of function "printf"
    " printf("bye\n");"
             ^
  ./decl_parsing/atexit/atexit.c:8:5: warning: control reaches end of non-void function p_bye
    "p_bye()"
        ^
  ./decl_parsing/atexit/atexit.c:15:12: warning: implicit declaration of function "atexit"
    " atexit(p_hi);"
               ^
  ./decl_parsing/atexit/atexit.c:13:4: warning: control reaches end of non-void function main
    "main()"
       ^
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './atexit.out | ./stdoutcheck.pl '^bye$' '^beet$'' failed
fail: ./decl_parsing/func_array.c
  ./decl_parsing/func_array.c:11:25: warning: implicit declaration of function "printf"
    " void p1(int i){printf("%s %d\n", __func__, i);}"
                            ^
  ./decl_parsing/func_array.c:12:25: warning: implicit declaration of function "printf"
    " void p2(int i){printf("%s %d\n", __func__, i);}"
                            ^
  ./decl_parsing/func_array.c:13:25: warning: implicit declaration of function "printf"
    " void p3(int i){printf("%s %d\n", __func__, i);}"
                            ^
  ./decl_parsing/func_array.c:14:25: warning: implicit declaration of function "printf"
    " void p4(int i){printf("%s %d\n", __func__, i);}"
                            ^
  ./decl_parsing/func_array.c:18:11: warning: assignment type mismatch: int (*)(int) <-- void (*)(int i)
    " f[0] = p1;"
              ^
  ./decl_parsing/func_array.c:19:11: warning: assignment type mismatch: int (*)(int) <-- void (*)(int i)
    " f[1] = p2;"
              ^
  ./decl_parsing/func_array.c:20:11: warning: assignment type mismatch: int (*)(int) <-- void (*)(int i)
    " f[2] = p3;"
              ^
  ./decl_parsing/func_array.c:21:11: warning: assignment type mismatch: int (*)(int) <-- void (*)(int i)
    " f[3] = p4;"
              ^
  ./decl_parsing/func_array.c:16:4: warning: control reaches end of non-void function main
    "main()"
       ^
  Floating point exception (core dumped)
  mismatching output counts at ./stdoutcheck.pl line 15.
  timeout: child returned 65280
  ./test.pl: command './func_array.out | ./stdoutcheck.pl 'p1 1' 'p2 2' 'p3 3' 'p4 4'' failed
pass: ./format/long.c
pass: ./format/fmt.c
pass: ./format/str.c
fail: ./format/fmt_invalid.c
  check /error: variadic argument out of bounds/ not found in warnings on line 3
  check /error: format variadic argument before string/ not found in warnings on line 4
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./format/fmt_invalid.c' failed
fail: ./format/non_variadic.c
  check /error: non variadic/ not found in warnings on line 3
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./format/non_variadic.c' failed
pass: ./format/too_few.c
pass: ./format/non_trivial_fmt.c
pass: ./format/too_many.c
pass: ./format/mismatch.c
pass: ./format/null.c
pass: ./scope/implicit_in_init.c
pass: ./scope/scope.c
pass: ./scope/stmt_init.c
pass: ./scope/symtable.c
pass: ./gen/flag_argument.c
pass: ./gen/for_C99.c
fail: ./gen/x86_64/idiv.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./gen/x86_64/idiv.c' failed
fail: ./gen/deref.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./gen/deref.c' failed
fail: ./gen/cmp.c
  ./gen/cmp.c:8:8: warning: implicit declaration of function "write"
    " write(1, "\n", 1);"
           ^
  ./gen/cmp.c:6:2: warning: control reaches end of non-void function nl
    "nl()"
     ^
  ./gen/cmp.c:13:8: warning: implicit declaration of function "write"
    " write(1, &"0123456789"[argc], 1);"
           ^
  ./gen/cmp.c:18:31: warning: implicit declaration of function "strlen"
    "  write(1, argv[i], strlen(argv[i])), nl();"
                                  ^
  ./gen/cmp.c:11:4: warning: control reaches end of non-void function main
    "main(int argc, char **argv, char **envp)"
       ^
  ./gen/cmp.c:11:34: warning: "envp" never read
    "main(int argc, char **argv, char **envp)"
                                     ^
  timeout: child returned 256
  ./test.pl: command './cmp.out hi | sed -n 1p | grep '^1'' failed
pass: ./gen/stmt_expr_with_stmt.c
fail: ./other/alphabet.c
  ./other/alphabet.c:4:1: error: can't find include file <stdlib.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./alphabet.out ./other/alphabet.c' failed
fail: ./other/array_addressof.c
  ./other/array_addressof.c:4:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./other/array_addressof.c -o ./array_addressof.out' failed
fail: ./other/__file__.c
  ./other/__file__.c:6:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./__file__.out ./other/__file__.c' failed
fail: ./other/_Generic_const.c
  ./other/_Generic_const.c:9:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./_Generic_const.out ./other/_Generic_const.c' failed
pass: ./other/addr.c
pass: ./other/_Static_assert.c
fail: ./other/_Generic.c
  ./other/_Generic.c:15:17: warning: implicit declaration of function "printf"
    "  printf(_Generic(i, char *: "%s", int: "%d"), i);"
                    ^
  ./other/_Generic.c:20:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./_Generic.out ./other/_Generic.c' failed
fail: ./other/__asm__.c
  ./other/__asm__.c:8:16: ICW parse.c:239 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./other/__asm__.c:12:9: warning: implicit declaration of function "__asm__"
    "        );"
            ^
  ./other/__asm__.c:8:16: ICW parse.c:239 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./other/__asm__.c:12:9: warning: implicit declaration of function "__asm__"
    "        );"
            ^
  /tmp/file6F8ppp: In function `main':
  (.text+0xe): undefined reference to `__asm__'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./__asm__.out ./other/__asm__.c' failed
fail: ./other/assert.c
  ./other/assert.c:5:1: error: can't find include file <assert.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./assert.out ./other/assert.c' failed
pass: ./other/ar_addr.c
fail: ./other/atexit.c
  ./other/atexit.c:6:1: error: can't find include file <stdio.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./atexit.out ./other/atexit.c' failed
fail: ./other/assign_order.c
  ./other/assign_order.c:4:1: error: can't find include file <assert.h>
  ../ucc: cpp2/cpp returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -fno-const-fold -o ./assign_order.out ./other/assign_order.c' failed
pass: ./other/args_definitions.c
fail: ./other/array_size_check.c
  ./other/array_size_check.c:5:13: error: expecting token open_block, got comma (parse.c:816)
    "int printf(), abort();"
                ^
  ./other/array_size_check.c:5:13: error: expression expected, got comma (parse.c:246)
    "int printf(), abort();"
                ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./array_size_check.out ./other/array_size_check.c' failed
fail: ./C99/generic_default.c
  ./C99/generic_default.c:7:1: ICE fold.c:134 (FOLD_EXPR_NO_DECAY): no tree_type after fold (_Generic)
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./generic_default.out ./C99/generic_default.c' failed
pass: ./C99/C99_for.c
fail: ./C99/generic_simple.c
  ./C99/generic_simple.c:7:1: ICE ops/expr__Generic.c:36 (fold_expr__Generic): already chosen expr for _Generic
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./generic_simple.out ./C99/generic_simple.c' failed
fail: ./C99/enum_scope.c
  check /error: b not in scope/ not found in warnings on line 6
  timeout: child returned 256
  ./test.pl: command './check.sh -e ./C99/enum_scope.c' failed
fail: ./C99/generic_complex.c
  ./C99/generic_complex.c:9:28: error: trying to redefine union as struct (from ./C99/generic_complex.c:8:44)
    "    , char: 5, int(struct f): 1);"
                               ^
  ../ucc: cc1/cc1 returned 1
  ./C99/generic_complex.c:8:56: error: invalid indirection applied to int
    "    *(typeof((*(struct A { int (*i)(union f); } *)0).i))0"
                                                           ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -DS_OR_U=union  ./C99/generic_complex.c -o ./generic_complex.out; [ $? -eq 0 ]' failed
pass: ./C99/generic_nomatch.c
pass: ./C99/generic_dup.c
fail: ./bitfields/bitfield_warns.c
  ./bitfields/bitfield_warns.c:8:19: ICE parse_type.c:1084 (parse_decls_multi_type): TODO: field width
  ../ucc: cc1/cc1 caught signal 6
  timeout: child returned 256
  ./test.pl: command '../ucc ./bitfields/bitfield_warns.c' failed
pass: ./__builtin/bfa.c
pass: ./__builtin/is_signed.c
fail: ./__builtin/strlen_k.c
  ./__builtin/strlen_k.c:4:1: warning: control reaches end of non-void function q
    "q(){}"
    ^
  ./__builtin/strlen_k.c:9:9: warning: implicit declaration of function "strlen"
    " strlen(s);"
            ^
  ./__builtin/strlen_k.c:11:9: warning: too many arguments to implicitly (void)-function
    " q(strlen("yo"));"
            ^
  ../ucc: cc1/cc1 caught signal 11
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./strlen_k.out ./__builtin/strlen_k.c' failed
pass: ./__builtin/fno-builtin.c
fail: ./asm/call.c
  todo
  timeout: child returned 256
  ./test.pl: command 'echo todo; false' failed
pass: ./asm/call_ptr.c
pass: ./asm/abi_vararg_nulfptr.c
pass: ./asm/complex_math.c
pass: ./asm/memory.c
pass: ./asm/store.c
pass: ./asm/kjmp.c
pass: ./asm/call_or.c
pass: ./asm/expr-if.c
pass: ./asm/computed_goto.c
pass: ./asm/x86_shift.c
pass: ./asm/compound_assign.c
pass: ./asm/different_sizes.c
pass: ./asm/mismatch_compound.c
pass: ./asm/cast.c
pass: ./asm/lea.c
pass: ./asm/asm_bend.c
pass: ./asm/goto.c
pass: ./asm/inc.c
pass: ./asm/load-time-constant.c
pass: ./asm/offsetof.c
pass: ./asm/cmp.c
pass: ./asm/compound_increment.c
pass: ./asm/assigns.c
pass: ./asm/pointers.c
pass: ./asm/shft.c
pass: ./asm/jmp.c
fail: ./asm/abi-test.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
pass: ./asm/div.c
pass: ./paths/reachable.c
fail: ./folding/array_param.c
  ./folding/array_param.c:4:23: error: negative array size
    "extern int f(int x[-1]); "
                          ^
  ../ucc: cc1/cc1 returned 1
  no error expected
  ./folding/array_param.c:4:23: error: negative array size
    "extern int f(int x[-1]); "
                          ^
  ../ucc: cc1/cc1 returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./folding/array_param.c 2>&1 | ./check.sh ./folding/array_param.c' failed
fail: ./folding/typedef_redef.c
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./folding/typedef_redef.c; [ $? -ne 0 ]' failed
pass: ./__asm__/escaped.c
pass: ./__asm__/extern.c
pass: ./__asm__/decl.c
fail: ./__asm__/multiple.c
  ./__asm__/multiple.c:8:5: ICW parse.c:239 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./__asm__/multiple.c:10:5: warning: implicit declaration of function "__asm__"
    "   "ret\n");"
        ^
  ./__asm__/multiple.c:11:8: warning: implicit declaration of function "abort"
    " abort();"
           ^
  ./__asm__/multiple.c:6:4: warning: control reaches end of non-void function main
    "main()"
       ^
  /tmp/filefS1UUx: In function `main':
  (.text+0x1d): undefined reference to `__asm__'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./multiple.out ./__asm__/multiple.c' failed
fail: ./__asm__/gasm_order.c
  ./__asm__/gasm_order.c:5:1: warning: control reaches end of non-void function A
    "A(){}"
    ^
  ./__asm__/gasm_order.c:7:1: warning: control reaches end of non-void function C
    "C(){}"
    ^
  ./__asm__/gasm_order.c:9:1: warning: control reaches end of non-void function E
    "E(){}"
    ^
  /tmp/fileQ1bNXN: Assembler messages:
  /tmp/fileQ1bNXN:2: Error: junk at end of line, first unrecognized character is `0'
  ../ucc: as returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc -c ./__asm__/gasm_order.c' failed
fail: ./__asm__/inline.c
  ./__asm__/inline.c:6:5: ICW parse.c:239 (parse_expr_primary): token_asm - redirect to builtin instead of identifier
  ./__asm__/inline.c:6:7: warning: implicit declaration of function "__asm__"
    " asm("movl $3, %eax");"
          ^
  ./__asm__/inline.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  /tmp/fileyOWneK: In function `main':
  (.text+0xe): undefined reference to `__asm__'
  ../ucc: ld returned 1
  timeout: child returned 256
  ./test.pl: command '../ucc ./__asm__/inline.c -o ./inline.out' failed
pass: ./__asm__/global.c
fail: ./__asm__/gasm.c
  Died at ./asmcheck.pl line 6.
  timeout: child returned 512
  ./test.pl: command './asmcheck.pl ./__asm__/gasm.c' failed
pass: ./decay/assign.c
fail: ./decay/typeof.c
  ./decay/typeof.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./decay/typeof.c:7:12: warning: "b" never written to
    " typeof(a) b;"
               ^
  ./decay/typeof.c:7:12: warning: "b" never read
    " typeof(a) b;"
               ^
  ./decay/typeof.c:8:17: warning: "c" never written to
    " typeof(int[4]) c;"
                    ^
  ./decay/typeof.c:8:17: warning: "c" never read
    " typeof(int[4]) c;"
                    ^
  ./decay/typeof.c:4:4: warning: control reaches end of non-void function main
    "main()"
       ^
  ./decay/typeof.c:7:12: warning: "b" never written to
    " typeof(a) b;"
               ^
  ./decay/typeof.c:7:12: warning: "b" never read
    " typeof(a) b;"
               ^
  ./decay/typeof.c:8:17: warning: "c" never written to
    " typeof(int[4]) c;"
                    ^
  ./decay/typeof.c:8:17: warning: "c" never read
    " typeof(int[4]) c;"
                    ^
  timeout: child returned 256
  ./test.pl: command '[ `../ucc -S -o- ./decay/typeof.c | grep 'subq' | awk '{print $2}' | grep -o '[0-9]\+'` -ge 48 ]' failed
pass: ./decay/array.c
pass: ./decay/unary_addr_and_sizeof.c
pass: ./cil/6.c
pass: ./cil/4.c
fail: ./cil/gcc_8.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
fail: ./cil/9.c
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./9.out ./cil/9.c && ./9.out' failed
fail: ./cil/gcc_6.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
pass: ./cil/7.c
fail: ./cil/gcc_1.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
fail: ./cil/gcc_7.c
  TODO
  timeout: child returned 256
  ./test.pl: command 'echo TODO; false' failed
pass: ./cil/2.c
pass: ./cil/1.c
pass: ./cil/5.c
pass: ./cil/gcc_3.c
pass: ./cil/gcc_2.c
pass: ./cil/cil_1.c
pass: ./cil/8.c
pass: ./cil/gcc_5.c
fail: ./cil/gcc_4.c
  ./cil/gcc_4.c:4:20: warning: dead code after goto (expr)
    " return ({goto L; 0;}) && ({L: 5;});"
                       ^
  ./cil/gcc_4.c:4:32: warning: unused expression (val)
    " return ({goto L; 0;}) && ({L: 5;});"
                                   ^
  timeout: child returned 256
  ./test.pl: command '../ucc -o ./gcc_4.out ./cil/gcc_4.c && (./gcc_4.out; [ $? -eq 5 ])' failed
pass: ./cil/3.c
