#!/usr/bin/perl
use warnings;

sub asmstrlen
{
	shift =~ /"([^"]+)"/;
	return length $1;
}

sub itemcount
{
  my $x = shift;
  $x =~ s/[@#].*//;
  $x =~ s/[^,]//g;
  return 1 + length $x;
}

my %types = (
	"byte" => sub { return 1 * itemcount shift },
	"word" => sub { return 2 * itemcount shift },
	"short" => sub { return 2 * itemcount shift },
	"long" => sub { return 4 * itemcount shift },
	"quad" => sub { return 8 * itemcount shift },
	"ascii" => sub { return asmstrlen shift },
	"asciz" => sub { return 1 + asmstrlen shift },
);

my $off = 0;
while(<>){
	my $orig = $_;

	s/#.*//;
	if(/\.([a-z]+)\s+(.*)/){
		my($ty, $rest) = ($1, $2);

		if($ty eq 'section'){
			$off = 0;
		}else{
			my $sub = $types{$ty};

			if(defined $sub){
				my $sz = $sub->($rest);
				print "/* offset = $off */ ";
				$off += $sz;
			}
		}
	}

	print $orig;
}
