const.o: const.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 const.h cc1.h
decl.o: decl.c ../util/util.h ../util/alloc.h ../util/platform.h \
 ../util/dynarray.h data_structs.h tree.h expr.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h macros.h const.h
expr.o: expr.c ../util/util.h ../util/alloc.h data_structs.h tree.h \
 expr.h ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h cc1.h
fold.o: fold.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 cc1.h fold.h fold_sym.h ../util/platform.h const.h ../util/alloc.h \
 ../util/dynarray.h ../util/dynmap.h sue.h ops/__builtin.h
fold_sym.o: fold_sym.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 cc1.h fold_sym.h ../util/platform.h
gen_c.o: gen_c.c
gen_str.o: gen_str.c ../util/util.h ../util/platform.h data_structs.h \
 tree.h expr.h ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h macros.h cc1.h sue.h gen_str.h str.h const.h
gen_style.o: gen_style.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 cc1.h gen_style.h
parse.o: parse.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 tokenise.h parse.h ../util/alloc.h tokconv.h cc1.h ../util/dynarray.h \
 sue.h parse_type.h const.h
parse_attr.o: parse_attr.c
parse_type.o: parse_type.c ../util/util.h ../util/alloc.h \
 ../util/dynarray.h data_structs.h tree.h expr.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h typedef.h tokenise.h \
 tokconv.h sue.h cc1.h parse.h parse_type.h parse_attr.c
stmt.o: stmt.c ../util/util.h ../util/alloc.h data_structs.h tree.h \
 expr.h ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h
str.o: str.c ../util/util.h ../util/alloc.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 str.h
sue.o: sue.c ../util/alloc.h ../util/util.h ../util/dynarray.h \
 data_structs.h tree.h expr.h ops/expr_addr.h ops/expr_assign.h \
 ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h sue.h cc1.h
sym.o: sym.c ../util/util.h data_structs.h tree.h expr.h ops/expr_addr.h \
 ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h ops/expr_funcall.h \
 ops/expr_identifier.h ops/expr_if.h ops/expr_op.h ops/expr_sizeof.h \
 ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h ops/stmt_case.h \
 ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h ops/stmt_do.h \
 ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h ops/stmt_if.h \
 ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h ops/stmt_switch.h \
 ops/stmt_while.h ops/stmt_continue.h sym.h decl.h ../util/alloc.h \
 macros.h ../util/dynarray.h typedef.h
tokconv.o: tokconv.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 tokenise.h tokconv.h macros.h cc1.h
tokenise.o: tokenise.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 tokenise.h ../util/alloc.h str.h cc1.h
tree.o: tree.c ../util/alloc.h ../util/util.h data_structs.h tree.h \
 expr.h ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h \
 ops/expr_comma.h ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h \
 ops/expr_op.h ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h \
 ops/stmt_break.h ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h \
 ops/stmt_default.h ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h \
 ops/stmt_goto.h ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h \
 ops/stmt_return.h ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h \
 sym.h decl.h macros.h ../util/platform.h sue.h
typedef.o: typedef.c ../util/util.h data_structs.h tree.h expr.h \
 ops/expr_addr.h ops/expr_assign.h ops/expr_cast.h ops/expr_comma.h \
 ops/expr_funcall.h ops/expr_identifier.h ops/expr_if.h ops/expr_op.h \
 ops/expr_sizeof.h ops/expr_val.h ops/expr_stmt.h stmt.h ops/stmt_break.h \
 ops/stmt_case.h ops/stmt_case_range.h ops/stmt_code.h ops/stmt_default.h \
 ops/stmt_do.h ops/stmt_expr.h ops/stmt_for.h ops/stmt_goto.h \
 ops/stmt_if.h ops/stmt_label.h ops/stmt_noop.h ops/stmt_return.h \
 ops/stmt_switch.h ops/stmt_while.h ops/stmt_continue.h sym.h decl.h \
 ../util/alloc.h typedef.h
__builtin.o: ops/__builtin.c ops/../../util/util.h \
 ops/../../util/dynarray.h ops/../../util/alloc.h ops/../data_structs.h \
 ops/../tree.h ops/../expr.h ops/../ops/expr_addr.h \
 ops/../ops/expr_assign.h ops/../ops/expr_cast.h ops/../ops/expr_comma.h \
 ops/../ops/expr_funcall.h ops/../ops/expr_identifier.h \
 ops/../ops/expr_if.h ops/../ops/expr_op.h ops/../ops/expr_sizeof.h \
 ops/../ops/expr_val.h ops/../ops/expr_stmt.h ops/../stmt.h \
 ops/../ops/stmt_break.h ops/../ops/stmt_case.h \
 ops/../ops/stmt_case_range.h ops/../ops/stmt_code.h \
 ops/../ops/stmt_default.h ops/../ops/stmt_do.h ops/../ops/stmt_expr.h \
 ops/../ops/stmt_for.h ops/../ops/stmt_goto.h ops/../ops/stmt_if.h \
 ops/../ops/stmt_label.h ops/../ops/stmt_noop.h ops/../ops/stmt_return.h \
 ops/../ops/stmt_switch.h ops/../ops/stmt_while.h \
 ops/../ops/stmt_continue.h ops/../sym.h ops/../decl.h ops/__builtin.h
